/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asdtemp;

import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ajayj
 */
public class AddCFLTC extends javax.swing.JFrame {

    /**
     * Creates new form FAQ
     */
    public AddCFLTC() {
        initComponents();
        this.setLocationRelativeTo(null);
        fillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_toppanel = new javax.swing.JPanel();
        l_title = new javax.swing.JLabel();
        img_back = new javax.swing.JLabel();
        p_main = new javax.swing.JPanel();
        l_nameCFLTC = new javax.swing.JLabel();
        l_addrCFLTC = new javax.swing.JLabel();
        l_contactNum = new javax.swing.JLabel();
        l_selectDistrict = new javax.swing.JLabel();
        l_bedNum = new javax.swing.JLabel();
        l_categ = new javax.swing.JLabel();
        l_nodalOffice = new javax.swing.JLabel();
        tf_nameCFLTC = new javax.swing.JTextField();
        sp_addrCFLTC = new javax.swing.JScrollPane();
        ta_addrCFLTC = new javax.swing.JTextArea();
        tf_contactNum = new javax.swing.JTextField();
        cb_selectDistrict = new javax.swing.JComboBox<>();
        tf_bedNum = new javax.swing.JTextField();
        cb_categ = new javax.swing.JComboBox<>();
        tf_nodalOffice = new javax.swing.JTextField();
        b_addCFLTC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 730));
        setResizable(false);
        getContentPane().setLayout(null);

        p_toppanel.setBackground(new java.awt.Color(46, 49, 49));
        p_toppanel.setLayout(null);

        l_title.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        l_title.setForeground(new java.awt.Color(255, 255, 255));
        l_title.setText("Add CFLTCs");
        p_toppanel.add(l_title);
        l_title.setBounds(70, 10, 170, 41);

        img_back.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        img_back.setForeground(new java.awt.Color(255, 255, 255));
        img_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/back2.png"))); // NOI18N
        img_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        img_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_backMouseClicked(evt);
            }
        });
        p_toppanel.add(img_back);
        img_back.setBounds(20, 10, 40, 40);

        getContentPane().add(p_toppanel);
        p_toppanel.setBounds(0, 0, 900, 60);

        p_main.setBackground(new java.awt.Color(232, 236, 241));
        p_main.setMinimumSize(new java.awt.Dimension(900, 700));
        p_main.setPreferredSize(new java.awt.Dimension(900, 700));

        l_nameCFLTC.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        l_nameCFLTC.setText("CFLTC Name");

        l_addrCFLTC.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        l_addrCFLTC.setText("Address of CFLTC");

        l_contactNum.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        l_contactNum.setText("Contact Number");

        l_selectDistrict.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        l_selectDistrict.setText("CFLTC District");

        l_bedNum.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        l_bedNum.setText("Number of Beds available");

        l_categ.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        l_categ.setText("Select Category");

        l_nodalOffice.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        l_nodalOffice.setText("Name of Nodal Office in charge");

        tf_nameCFLTC.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        ta_addrCFLTC.setColumns(20);
        ta_addrCFLTC.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        ta_addrCFLTC.setLineWrap(true);
        ta_addrCFLTC.setRows(5);
        sp_addrCFLTC.setViewportView(ta_addrCFLTC);

        tf_contactNum.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        tf_contactNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_contactNumKeyPressed(evt);
            }
        });

        cb_selectDistrict.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        cb_selectDistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_selectDistrictActionPerformed(evt);
            }
        });

        tf_bedNum.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        tf_bedNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_bedNumKeyPressed(evt);
            }
        });

        cb_categ.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        cb_categ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Free", "Paid" }));

        tf_nodalOffice.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        b_addCFLTC.setBackground(new java.awt.Color(23, 162, 184));
        b_addCFLTC.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        b_addCFLTC.setText("Add CFLTC");
        b_addCFLTC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_addCFLTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_addCFLTCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_mainLayout = new javax.swing.GroupLayout(p_main);
        p_main.setLayout(p_mainLayout);
        p_mainLayout.setHorizontalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_mainLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(l_selectDistrict)
                        .addGap(200, 200, 200)
                        .addComponent(cb_selectDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_mainLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(l_nameCFLTC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(tf_nameCFLTC, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_mainLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(l_addrCFLTC, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(sp_addrCFLTC, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_mainLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(b_addCFLTC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(p_mainLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(l_contactNum, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(180, 180, 180)
                            .addComponent(tf_contactNum, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(p_mainLayout.createSequentialGroup()
                                .addComponent(l_nodalOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_nodalOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_mainLayout.createSequentialGroup()
                                .addComponent(l_categ, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_categ, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_mainLayout.createSequentialGroup()
                                .addComponent(l_bedNum, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_bedNum, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        p_mainLayout.setVerticalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_selectDistrict)
                    .addComponent(cb_selectDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_nameCFLTC)
                    .addComponent(tf_nameCFLTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_addrCFLTC)
                    .addComponent(sp_addrCFLTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_contactNum)
                    .addComponent(tf_contactNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_bedNum)
                    .addComponent(tf_bedNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_categ)
                    .addComponent(cb_categ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_nodalOffice)
                    .addComponent(tf_nodalOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(b_addCFLTC))
        );

        getContentPane().add(p_main);
        p_main.setBounds(0, 60, 900, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_selectDistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_selectDistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_selectDistrictActionPerformed

    private void b_addCFLTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_addCFLTCActionPerformed
        int cfltc_district = cb_selectDistrict.getSelectedIndex()+1;
        String cfltc_name = tf_nameCFLTC.getText();
        String cfltc_addr = ta_addrCFLTC.getText();
        String cfltc_contactNum = tf_contactNum.getText();
        int cfltc_bedNum = Integer.parseInt(tf_bedNum.getText());
        String cfltc_category = cb_categ.getSelectedItem().toString();
        String cfltc_nodalOffice = tf_nodalOffice.getText();
        
        try{
            if(cfltc_contactNum.length()!=10)
            JOptionPane.showMessageDialog(null,"Provide a valid 10 digit mobile number","Invalid Phone Number",JOptionPane.ERROR_MESSAGE);
            else
            {
            Connection con = new Connector().getCon();
            PreparedStatement ps = con.prepareStatement("INSERT INTO `asdproject`.`cfltc` (`cfltc_district_id`, `cfltc_name`, `cfltc_address`, `cfltc_contactnum`, `cfltc_capacity`, `cfltc_category`, `cfltc_officer`) VALUES (?, ?, ?, ?, ?, ?, ?);");
            ps.setInt(1,cfltc_district);
            ps.setString(2,cfltc_name);
            ps.setString(3,cfltc_addr);
            ps.setString(4,cfltc_contactNum);
            ps.setInt(5,cfltc_bedNum);
            ps.setString(6, cfltc_category);
            ps.setString(7,cfltc_nodalOffice);
            
            int rs = ps.executeUpdate();
            
            if(rs != 0){
               JOptionPane.showMessageDialog(null,"CFLTC Added Sucessfully");
               tf_nameCFLTC.setText("");
               ta_addrCFLTC.setText("");
               tf_contactNum.setText("");
               tf_bedNum.setText("");
               tf_nodalOffice.setText("");
            }
            else{
                JOptionPane.showMessageDialog(null,"CFLTC Not Added","Error",JOptionPane.ERROR_MESSAGE);
            }
            }
            
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Class Missing. Contact System Admin.");
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null,"Unknown Error. Contact System Admin.");
        } 
    }//GEN-LAST:event_b_addCFLTCActionPerformed

    private void img_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_backMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_img_backMouseClicked

    private void tf_contactNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_contactNumKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c))
            tf_contactNum.setEditable(false);
        else
            tf_contactNum.setEditable(true);  
    }//GEN-LAST:event_tf_contactNumKeyPressed

    private void tf_bedNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_bedNumKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(Character.isLetter(c))
            tf_bedNum.setEditable(false);
        else
           tf_bedNum.setEditable(true);  
    }//GEN-LAST:event_tf_bedNumKeyPressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddCFLTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddCFLTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddCFLTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddCFLTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddCFLTC().setVisible(true);
//            }
//        });
//    }
    private void fillCombo(){
        try{
                 
                 Connection con = new Connector().getCon();
                 PreparedStatement ps=con.prepareStatement("SELECT dist_name FROM asdproject.districts;");
                 ResultSet rs = ps.executeQuery();
                 int size = 0;
                 if (rs != null) 
                {
                    rs.last();    // moves cursor to the last row
                    size = rs.getRow(); // get row id 
                }
                rs.first();
                String[] distnames = new String[size];
                int i=0;
                do{
                    distnames[i++]=rs.getString(1);
                }while(rs.next());
                cb_selectDistrict.setModel(new javax.swing.DefaultComboBoxModel<>(distnames));
  
   
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Class Missing. Contact System Admin.");
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null,"Unknown Error. Contact System Admin.");
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_addCFLTC;
    private javax.swing.JComboBox<String> cb_categ;
    private javax.swing.JComboBox<String> cb_selectDistrict;
    private javax.swing.JLabel img_back;
    private javax.swing.JLabel l_addrCFLTC;
    private javax.swing.JLabel l_bedNum;
    private javax.swing.JLabel l_categ;
    private javax.swing.JLabel l_contactNum;
    private javax.swing.JLabel l_nameCFLTC;
    private javax.swing.JLabel l_nodalOffice;
    private javax.swing.JLabel l_selectDistrict;
    private javax.swing.JLabel l_title;
    private javax.swing.JPanel p_main;
    private javax.swing.JPanel p_toppanel;
    private javax.swing.JScrollPane sp_addrCFLTC;
    private javax.swing.JTextArea ta_addrCFLTC;
    private javax.swing.JTextField tf_bedNum;
    private javax.swing.JTextField tf_contactNum;
    private javax.swing.JTextField tf_nameCFLTC;
    private javax.swing.JTextField tf_nodalOffice;
    // End of variables declaration//GEN-END:variables
}
