/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asdtemp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author ajayj
 */
public class AdminDash extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public AdminDash(String n, int i) {
        name=n;
        id=i;
        initComponents();
        this.setLocationRelativeTo(null);
        l_username.setText(name); 
        fetch();
   }

    private void fetch()
    {
         try
    {
        Connection con=new Connector().getCon();
        PreparedStatement ps=con.prepareStatement("SELECT count(c_covid_status) FROM asdproject.citizen_list WHERE c_covid_status='Died';");
        ResultSet rs=ps.executeQuery();
        if(rs.next())
        l_death_count.setText(rs.getString(1));
        ps=con.prepareStatement("SELECT count(c_covid_status) FROM asdproject.citizen_list WHERE c_covid_status='Positive';");
         rs=ps.executeQuery();
        if(rs.next())
        l_active_count.setText(rs.getString(1));
        ps=con.prepareStatement("SELECT count(sl_num) FROM asdproject.total_recoverd_list;");
         rs=ps.executeQuery();
        if(rs.next())
        l_recovered_count.setText(rs.getString(1));
        ps=con.prepareStatement("SELECT count(sl_no) FROM asdproject.total_affected_list;");
         rs=ps.executeQuery();
        if(rs.next())
        l_affected_count.setText(rs.getString(1));
    }
        catch(ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null,"Class Error. Contact System Admin");
        } catch(SQLException e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Unknown Error. Contact System Admin");
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img_user = new javax.swing.JLabel();
        img_virus = new javax.swing.JLabel();
        p_sidepanel = new javax.swing.JPanel();
        p_manage = new javax.swing.JPanel();
        l_manage = new javax.swing.JLabel();
        p_healthworkers = new javax.swing.JPanel();
        l_healthworkers = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        p_testingcenters = new javax.swing.JPanel();
        l_testingcenters = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        p_cfltcs = new javax.swing.JPanel();
        l_cfltcs = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        p_manageorders = new javax.swing.JPanel();
        l_cfltcs1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        p_managecommunications = new javax.swing.JPanel();
        l_cfltcs2 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        p_hotspots = new javax.swing.JPanel();
        l_hotspots = new javax.swing.JLabel();
        p_volunteers = new javax.swing.JPanel();
        l_healthworkers1 = new javax.swing.JLabel();
        p_toppanel = new javax.swing.JPanel();
        p_userpanel = new javax.swing.JPanel();
        cb_useroptions = new javax.swing.JComboBox<>();
        l_username = new javax.swing.JLabel();
        l_designation = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l_title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        p_mainpanel = new javax.swing.JPanel();
        p_totconfirmed = new javax.swing.JPanel();
        l_totconfirmed = new javax.swing.JLabel();
        l_affected_count = new javax.swing.JLabel();
        p_recovered = new javax.swing.JPanel();
        l_recovered_count = new javax.swing.JLabel();
        l_recovered = new javax.swing.JLabel();
        p_deaths = new javax.swing.JPanel();
        l_death_count = new javax.swing.JLabel();
        l_deaths = new javax.swing.JLabel();
        p_activecases = new javax.swing.JPanel();
        l_activecases = new javax.swing.JLabel();
        l_active_count = new javax.swing.JLabel();
        b_refreshstats = new javax.swing.JButton();
        b_refresh = new javax.swing.JButton();

        img_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/50x50.png"))); // NOI18N
        img_user.setText("jLabel12");

        img_virus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/vir_60x60.png"))); // NOI18N
        img_virus.setText("jLabel22");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        p_sidepanel.setBackground(new java.awt.Color(46, 49, 49));
        p_sidepanel.setToolTipText("");
        p_sidepanel.setLayout(null);

        p_manage.setBackground(new java.awt.Color(46, 49, 49));
        p_manage.setForeground(new java.awt.Color(46, 49, 49));

        l_manage.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_manage.setForeground(new java.awt.Color(255, 255, 255));
        l_manage.setText("Manage");
        l_manage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_manageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p_manageLayout = new javax.swing.GroupLayout(p_manage);
        p_manage.setLayout(p_manageLayout);
        p_manageLayout.setHorizontalGroup(
            p_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_manageLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(l_manage)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        p_manageLayout.setVerticalGroup(
            p_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_manageLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_manage)
                .addContainerGap())
        );

        p_sidepanel.add(p_manage);
        p_manage.setBounds(0, 0, 250, 50);

        p_healthworkers.setBackground(new java.awt.Color(46, 49, 49));
        p_healthworkers.setForeground(new java.awt.Color(46, 49, 49));
        p_healthworkers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_healthworkers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_healthworkersMouseClicked(evt);
            }
        });

        l_healthworkers.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_healthworkers.setForeground(new java.awt.Color(255, 255, 255));
        l_healthworkers.setText("Health Workers");

        jSeparator1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSeparator1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p_healthworkersLayout = new javax.swing.GroupLayout(p_healthworkers);
        p_healthworkers.setLayout(p_healthworkersLayout);
        p_healthworkersLayout.setHorizontalGroup(
            p_healthworkersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addGroup(p_healthworkersLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(l_healthworkers)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_healthworkersLayout.setVerticalGroup(
            p_healthworkersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_healthworkersLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(l_healthworkers)
                .addContainerGap())
        );

        p_sidepanel.add(p_healthworkers);
        p_healthworkers.setBounds(0, 50, 250, 50);

        p_testingcenters.setBackground(new java.awt.Color(46, 49, 49));
        p_testingcenters.setForeground(new java.awt.Color(46, 49, 49));
        p_testingcenters.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_testingcenters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_testingcentersMouseClicked(evt);
            }
        });

        l_testingcenters.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_testingcenters.setForeground(new java.awt.Color(255, 255, 255));
        l_testingcenters.setText("Testing Centers");

        javax.swing.GroupLayout p_testingcentersLayout = new javax.swing.GroupLayout(p_testingcenters);
        p_testingcenters.setLayout(p_testingcentersLayout);
        p_testingcentersLayout.setHorizontalGroup(
            p_testingcentersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_testingcentersLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(l_testingcenters)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        p_testingcentersLayout.setVerticalGroup(
            p_testingcentersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_testingcentersLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_testingcenters)
                .addContainerGap())
        );

        p_sidepanel.add(p_testingcenters);
        p_testingcenters.setBounds(0, 200, 250, 50);

        jPanel12.setBackground(new java.awt.Color(46, 49, 49));
        jPanel12.setForeground(new java.awt.Color(46, 49, 49));

        p_cfltcs.setBackground(new java.awt.Color(46, 49, 49));
        p_cfltcs.setForeground(new java.awt.Color(46, 49, 49));
        p_cfltcs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_cfltcs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_cfltcsMouseClicked(evt);
            }
        });

        l_cfltcs.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_cfltcs.setForeground(new java.awt.Color(255, 255, 255));
        l_cfltcs.setText("CFLTCs");

        javax.swing.GroupLayout p_cfltcsLayout = new javax.swing.GroupLayout(p_cfltcs);
        p_cfltcs.setLayout(p_cfltcsLayout);
        p_cfltcsLayout.setHorizontalGroup(
            p_cfltcsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_cfltcsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(l_cfltcs)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        p_cfltcsLayout.setVerticalGroup(
            p_cfltcsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_cfltcsLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(l_cfltcs)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_cfltcs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(p_cfltcs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        p_sidepanel.add(jPanel12);
        jPanel12.setBounds(0, 250, 250, 59);

        jPanel15.setBackground(new java.awt.Color(46, 49, 49));
        jPanel15.setForeground(new java.awt.Color(46, 49, 49));

        p_manageorders.setBackground(new java.awt.Color(46, 49, 49));
        p_manageorders.setForeground(new java.awt.Color(46, 49, 49));
        p_manageorders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_manageorders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_manageordersMouseClicked(evt);
            }
        });

        l_cfltcs1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_cfltcs1.setForeground(new java.awt.Color(255, 255, 255));
        l_cfltcs1.setText("Orders");

        javax.swing.GroupLayout p_manageordersLayout = new javax.swing.GroupLayout(p_manageorders);
        p_manageorders.setLayout(p_manageordersLayout);
        p_manageordersLayout.setHorizontalGroup(
            p_manageordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_manageordersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_cfltcs1)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        p_manageordersLayout.setVerticalGroup(
            p_manageordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_manageordersLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(l_cfltcs1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_manageorders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(p_manageorders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        p_sidepanel.add(jPanel15);
        jPanel15.setBounds(0, 300, 250, 60);

        jPanel14.setBackground(new java.awt.Color(46, 49, 49));
        jPanel14.setForeground(new java.awt.Color(46, 49, 49));

        p_managecommunications.setBackground(new java.awt.Color(46, 49, 49));
        p_managecommunications.setForeground(new java.awt.Color(46, 49, 49));
        p_managecommunications.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_managecommunications.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_managecommunicationsMouseClicked(evt);
            }
        });

        l_cfltcs2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_cfltcs2.setForeground(new java.awt.Color(255, 255, 255));
        l_cfltcs2.setText("Communications");

        javax.swing.GroupLayout p_managecommunicationsLayout = new javax.swing.GroupLayout(p_managecommunications);
        p_managecommunications.setLayout(p_managecommunicationsLayout);
        p_managecommunicationsLayout.setHorizontalGroup(
            p_managecommunicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_managecommunicationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_cfltcs2)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        p_managecommunicationsLayout.setVerticalGroup(
            p_managecommunicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_managecommunicationsLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(l_cfltcs2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_managecommunications, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(p_managecommunications, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_sidepanel.add(jPanel14);
        jPanel14.setBounds(0, 350, 250, 51);

        jPanel16.setBackground(new java.awt.Color(46, 49, 49));
        jPanel16.setForeground(new java.awt.Color(46, 49, 49));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        p_sidepanel.add(jPanel16);
        jPanel16.setBounds(0, 400, 250, 50);

        jPanel17.setBackground(new java.awt.Color(46, 49, 49));
        jPanel17.setForeground(new java.awt.Color(46, 49, 49));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        p_sidepanel.add(jPanel17);
        jPanel17.setBounds(0, 450, 250, 50);

        p_hotspots.setBackground(new java.awt.Color(46, 49, 49));
        p_hotspots.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_hotspots.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_hotspotsMouseClicked(evt);
            }
        });

        l_hotspots.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_hotspots.setForeground(new java.awt.Color(255, 255, 255));
        l_hotspots.setText("Hotspots");

        javax.swing.GroupLayout p_hotspotsLayout = new javax.swing.GroupLayout(p_hotspots);
        p_hotspots.setLayout(p_hotspotsLayout);
        p_hotspotsLayout.setHorizontalGroup(
            p_hotspotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hotspotsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(l_hotspots, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        p_hotspotsLayout.setVerticalGroup(
            p_hotspotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_hotspotsLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_hotspots)
                .addContainerGap())
        );

        p_sidepanel.add(p_hotspots);
        p_hotspots.setBounds(0, 150, 250, 50);

        p_volunteers.setBackground(new java.awt.Color(46, 49, 49));
        p_volunteers.setForeground(new java.awt.Color(46, 49, 49));
        p_volunteers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_volunteers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_volunteersMouseClicked(evt);
            }
        });

        l_healthworkers1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_healthworkers1.setForeground(new java.awt.Color(255, 255, 255));
        l_healthworkers1.setText("Volunteers");

        javax.swing.GroupLayout p_volunteersLayout = new javax.swing.GroupLayout(p_volunteers);
        p_volunteers.setLayout(p_volunteersLayout);
        p_volunteersLayout.setHorizontalGroup(
            p_volunteersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_volunteersLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(l_healthworkers1)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        p_volunteersLayout.setVerticalGroup(
            p_volunteersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_volunteersLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_healthworkers1)
                .addContainerGap())
        );

        p_sidepanel.add(p_volunteers);
        p_volunteers.setBounds(0, 100, 250, 50);

        getContentPane().add(p_sidepanel);
        p_sidepanel.setBounds(0, 60, 250, 1260);

        p_toppanel.setBackground(new java.awt.Color(255, 255, 255));

        p_userpanel.setBackground(new java.awt.Color(46, 49, 49));
        p_userpanel.setForeground(new java.awt.Color(46, 49, 49));
        p_userpanel.setLayout(null);

        cb_useroptions.setBackground(new java.awt.Color(46, 49, 49));
        cb_useroptions.setForeground(new java.awt.Color(46, 49, 49));
        cb_useroptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Home", "Change Password", "Logout" }));
        cb_useroptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_useroptionsActionPerformed(evt);
            }
        });
        p_userpanel.add(cb_useroptions);
        cb_useroptions.setBounds(120, 40, 130, 19);

        l_username.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_username.setForeground(new java.awt.Color(255, 255, 255));
        l_username.setText("User Name");
        p_userpanel.add(l_username);
        l_username.setBounds(70, 10, 80, 19);

        l_designation.setForeground(new java.awt.Color(255, 255, 255));
        l_designation.setText("Admin");
        p_userpanel.add(l_designation);
        l_designation.setBounds(70, 30, 40, 13);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/50x50.png"))); // NOI18N
        p_userpanel.add(jLabel2);
        jLabel2.setBounds(10, 10, 85, 50);

        l_title.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        l_title.setText("Kerala : Covid Analysis");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/vir_60x60.png"))); // NOI18N

        javax.swing.GroupLayout p_toppanelLayout = new javax.swing.GroupLayout(p_toppanel);
        p_toppanel.setLayout(p_toppanelLayout);
        p_toppanelLayout.setHorizontalGroup(
            p_toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_toppanelLayout.createSequentialGroup()
                .addComponent(p_userpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_title)
                .addContainerGap(327, Short.MAX_VALUE))
        );
        p_toppanelLayout.setVerticalGroup(
            p_toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_userpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_toppanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_title)
                .addGap(65, 65, 65))
            .addGroup(p_toppanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(p_toppanel);
        p_toppanel.setBounds(0, 0, 910, 60);

        p_mainpanel.setBackground(new java.awt.Color(232, 236, 241));

        p_totconfirmed.setBackground(new java.awt.Color(220, 53, 69));

        l_totconfirmed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_totconfirmed.setForeground(new java.awt.Color(255, 255, 255));
        l_totconfirmed.setText("Total Affected");

        l_affected_count.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        l_affected_count.setForeground(new java.awt.Color(255, 255, 255));
        l_affected_count.setText("0");

        javax.swing.GroupLayout p_totconfirmedLayout = new javax.swing.GroupLayout(p_totconfirmed);
        p_totconfirmed.setLayout(p_totconfirmedLayout);
        p_totconfirmedLayout.setHorizontalGroup(
            p_totconfirmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_totconfirmedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_totconfirmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_affected_count)
                    .addComponent(l_totconfirmed))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        p_totconfirmedLayout.setVerticalGroup(
            p_totconfirmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_totconfirmedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_affected_count)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_totconfirmed)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        p_recovered.setBackground(new java.awt.Color(40, 167, 69));

        l_recovered_count.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        l_recovered_count.setForeground(new java.awt.Color(255, 255, 255));
        l_recovered_count.setText("0");

        l_recovered.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_recovered.setForeground(new java.awt.Color(255, 255, 255));
        l_recovered.setText("Total Recovered");

        javax.swing.GroupLayout p_recoveredLayout = new javax.swing.GroupLayout(p_recovered);
        p_recovered.setLayout(p_recoveredLayout);
        p_recoveredLayout.setHorizontalGroup(
            p_recoveredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_recoveredLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_recoveredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_recovered_count)
                    .addComponent(l_recovered))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        p_recoveredLayout.setVerticalGroup(
            p_recoveredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_recoveredLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_recovered_count)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_recovered)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        p_deaths.setBackground(new java.awt.Color(23, 162, 184));

        l_death_count.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        l_death_count.setForeground(new java.awt.Color(255, 255, 255));
        l_death_count.setText("0");

        l_deaths.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_deaths.setForeground(new java.awt.Color(255, 255, 255));
        l_deaths.setText("Total Deaths");

        javax.swing.GroupLayout p_deathsLayout = new javax.swing.GroupLayout(p_deaths);
        p_deaths.setLayout(p_deathsLayout);
        p_deathsLayout.setHorizontalGroup(
            p_deathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_deathsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_deathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_death_count)
                    .addComponent(l_deaths))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_deathsLayout.setVerticalGroup(
            p_deathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_deathsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_death_count)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_deaths)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        p_activecases.setBackground(new java.awt.Color(255, 193, 7));

        l_activecases.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_activecases.setForeground(new java.awt.Color(255, 255, 255));
        l_activecases.setText("Active Cases");

        l_active_count.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        l_active_count.setForeground(new java.awt.Color(255, 255, 255));
        l_active_count.setText("0");

        javax.swing.GroupLayout p_activecasesLayout = new javax.swing.GroupLayout(p_activecases);
        p_activecases.setLayout(p_activecasesLayout);
        p_activecasesLayout.setHorizontalGroup(
            p_activecasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_activecasesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_activecasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_active_count)
                    .addComponent(l_activecases))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        p_activecasesLayout.setVerticalGroup(
            p_activecasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_activecasesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_active_count)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_activecases)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        b_refreshstats.setBackground(new java.awt.Color(46, 49, 49));
        b_refreshstats.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b_refreshstats.setForeground(new java.awt.Color(255, 255, 255));
        b_refreshstats.setText("Refresh Statistics");
        b_refreshstats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_refreshstatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_mainpanelLayout = new javax.swing.GroupLayout(p_mainpanel);
        p_mainpanel.setLayout(p_mainpanelLayout);
        p_mainpanelLayout.setHorizontalGroup(
            p_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainpanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(p_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_refreshstats)
                    .addGroup(p_mainpanelLayout.createSequentialGroup()
                        .addGroup(p_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p_activecases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_totconfirmed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(p_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p_deaths, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p_recovered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        p_mainpanelLayout.setVerticalGroup(
            p_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainpanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(b_refreshstats)
                .addGap(18, 18, 18)
                .addGroup(p_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_totconfirmed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_recovered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(p_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_activecases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_deaths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(951, Short.MAX_VALUE))
        );

        getContentPane().add(p_mainpanel);
        p_mainpanel.setBounds(251, 56, 660, 1260);

        b_refresh.setBackground(new java.awt.Color(46, 49, 49));
        b_refresh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b_refresh.setForeground(new java.awt.Color(255, 255, 255));
        b_refresh.setText("Refresh Statistics");
        b_refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_refreshActionPerformed(evt);
            }
        });
        getContentPane().add(b_refresh);
        b_refresh.setBounds(0, 0, 139, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l_manageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_manageMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_l_manageMouseClicked

    private void p_cfltcsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_cfltcsMouseClicked
        // TODO add your handling code here:
        new CFLTCs().setVisible(true);
    }//GEN-LAST:event_p_cfltcsMouseClicked

    private void p_hotspotsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_hotspotsMouseClicked
        // TODO add your handling code here:
        new Hotspots().setVisible(true);
    }//GEN-LAST:event_p_hotspotsMouseClicked

    private void p_testingcentersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_testingcentersMouseClicked
        // TODO add your handling code here:
        new TestingCenters().setVisible(true);
    }//GEN-LAST:event_p_testingcentersMouseClicked

    private void jSeparator1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSeparator1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jSeparator1MouseClicked

    private void p_healthworkersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_healthworkersMouseClicked
        new ManageHealthWorkers().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_p_healthworkersMouseClicked

    private void p_volunteersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_volunteersMouseClicked
        // TODO add your handling code here:
         new ManageVolunteers().setVisible(true);
    }//GEN-LAST:event_p_volunteersMouseClicked

    private void cb_useroptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_useroptionsActionPerformed
        // TODO add your handling code here:
        if(cb_useroptions.getSelectedIndex()==2)
            this.dispose();
    }//GEN-LAST:event_cb_useroptionsActionPerformed

    private void p_manageordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_manageordersMouseClicked
        // TODO add your handling code here:
        new ManageOrders().setVisible(true);
    }//GEN-LAST:event_p_manageordersMouseClicked

    private void p_managecommunicationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_managecommunicationsMouseClicked
        // TODO add your handling code here:
         new Communications(id,0).setVisible(true);
    }//GEN-LAST:event_p_managecommunicationsMouseClicked

    private void b_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_refreshActionPerformed
        // TODO add your handling code here:
        fetch();
        JOptionPane.showMessageDialog(null,"Values Updated With Latest Data!");
    }//GEN-LAST:event_b_refreshActionPerformed

    private void b_refreshstatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_refreshstatsActionPerformed
        // TODO add your handling code here:
        fetch();
         JOptionPane.showMessageDialog(null,"Values Updated With Latest Data!");
    }//GEN-LAST:event_b_refreshstatsActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdminDash().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_refresh;
    private javax.swing.JButton b_refreshstats;
    private javax.swing.JComboBox<String> cb_useroptions;
    private javax.swing.JLabel img_user;
    private javax.swing.JLabel img_virus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_active_count;
    private javax.swing.JLabel l_activecases;
    private javax.swing.JLabel l_affected_count;
    private javax.swing.JLabel l_cfltcs;
    private javax.swing.JLabel l_cfltcs1;
    private javax.swing.JLabel l_cfltcs2;
    private javax.swing.JLabel l_death_count;
    private javax.swing.JLabel l_deaths;
    private javax.swing.JLabel l_designation;
    private javax.swing.JLabel l_healthworkers;
    private javax.swing.JLabel l_healthworkers1;
    private javax.swing.JLabel l_hotspots;
    private javax.swing.JLabel l_manage;
    private javax.swing.JLabel l_recovered;
    private javax.swing.JLabel l_recovered_count;
    private javax.swing.JLabel l_testingcenters;
    private javax.swing.JLabel l_title;
    private javax.swing.JLabel l_totconfirmed;
    private javax.swing.JLabel l_username;
    private javax.swing.JPanel p_activecases;
    private javax.swing.JPanel p_cfltcs;
    private javax.swing.JPanel p_deaths;
    private javax.swing.JPanel p_healthworkers;
    private javax.swing.JPanel p_hotspots;
    private javax.swing.JPanel p_mainpanel;
    private javax.swing.JPanel p_manage;
    private javax.swing.JPanel p_managecommunications;
    private javax.swing.JPanel p_manageorders;
    private javax.swing.JPanel p_recovered;
    private javax.swing.JPanel p_sidepanel;
    private javax.swing.JPanel p_testingcenters;
    private javax.swing.JPanel p_toppanel;
    private javax.swing.JPanel p_totconfirmed;
    private javax.swing.JPanel p_userpanel;
    private javax.swing.JPanel p_volunteers;
    // End of variables declaration//GEN-END:variables
    private String name;
    private int id;
}
