/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asdtemp;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author ajayj
 */
public class CFLTCs extends javax.swing.JFrame {

    /**
     * Creates new form CFLTCs
     */
    public CFLTCs() {
        initComponents();
        this.setLocationRelativeTo(null);
        fetch();
    }
    private void fetch()
{
    DefaultCategoryDataset barChartData= new DefaultCategoryDataset();
        
         try
        {
             Connection con=new Connector().getCon();
             PreparedStatement stmt= con.prepareStatement("SELECT count(cf.cfltc_id), d.dist_name from asdproject.cfltc cf, asdproject.districts d where cf.cfltc_district_id=d.dist_id group by d.dist_name;");
             ResultSet rs=stmt.executeQuery();
             while(rs.next())
                  barChartData.setValue(rs.getInt(1), "CFLTC Count", rs.getString(2));
        }
       catch(Exception e)  
       {
           JOptionPane.showMessageDialog(null,"Chart Display Error");
       }        
        JFreeChart barChart= ChartFactory.createBarChart("CFLTC District Wise Statistics", "District", "Count", barChartData, PlotOrientation.HORIZONTAL, false, true, false);      
        CategoryPlot barchrt= barChart.getCategoryPlot();
//        ((BarRenderer)barchrt.getRenderer()).setBarPainter(new StandardBarPainter());
//        BarRenderer r = (BarRenderer)barChart.getCategoryPlot().getRenderer();
//        r.setSeriesPaint(0, Color.black);
         NumberAxis yAxis = (NumberAxis) barchrt.getRangeAxis();
         yAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());
        barchrt.setRangeGridlinePaint(Color.ORANGE);
        
        ChartPanel barPanel= new ChartPanel(barChart);
        jPanel1.removeAll();
        jPanel1.add(barPanel, BorderLayout.CENTER);
        jPanel1.validate();
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_toppanel = new javax.swing.JPanel();
        p_title = new javax.swing.JLabel();
        img_back = new javax.swing.JLabel();
        p_sidepanel = new javax.swing.JPanel();
        p_addcfltc = new javax.swing.JPanel();
        l_manage = new javax.swing.JLabel();
        p_monitorcfltc = new javax.swing.JPanel();
        l_healthworkers = new javax.swing.JLabel();
        p_removecfltc = new javax.swing.JPanel();
        l_cfltcs = new javax.swing.JLabel();
        p_testingcenters = new javax.swing.JPanel();
        p_updatechart = new javax.swing.JPanel();
        l_hotspots1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        p_contactcfltc = new javax.swing.JPanel();
        l_hotspots = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        p_toppanel.setBackground(new java.awt.Color(46, 49, 49));

        p_title.setBackground(new java.awt.Color(255, 255, 255));
        p_title.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        p_title.setForeground(new java.awt.Color(255, 255, 255));
        p_title.setText("Manage CFLTCs");

        img_back.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        img_back.setForeground(new java.awt.Color(255, 255, 255));
        img_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/back2.png"))); // NOI18N
        img_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        img_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p_toppanelLayout = new javax.swing.GroupLayout(p_toppanel);
        p_toppanel.setLayout(p_toppanelLayout);
        p_toppanelLayout.setHorizontalGroup(
            p_toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_toppanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(img_back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p_title)
                .addContainerGap(638, Short.MAX_VALUE))
        );
        p_toppanelLayout.setVerticalGroup(
            p_toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_toppanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p_toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_title))
                .addGap(117, 117, 117))
        );

        getContentPane().add(p_toppanel);
        p_toppanel.setBounds(0, 0, 910, 60);

        p_sidepanel.setBackground(new java.awt.Color(46, 49, 49));
        p_sidepanel.setToolTipText("");
        p_sidepanel.setLayout(null);

        p_addcfltc.setBackground(new java.awt.Color(46, 49, 49));
        p_addcfltc.setForeground(new java.awt.Color(46, 49, 49));
        p_addcfltc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_addcfltc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_addcfltcMouseClicked(evt);
            }
        });

        l_manage.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_manage.setForeground(new java.awt.Color(255, 255, 255));
        l_manage.setText("Add new ");

        javax.swing.GroupLayout p_addcfltcLayout = new javax.swing.GroupLayout(p_addcfltc);
        p_addcfltc.setLayout(p_addcfltcLayout);
        p_addcfltcLayout.setHorizontalGroup(
            p_addcfltcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_addcfltcLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(l_manage)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        p_addcfltcLayout.setVerticalGroup(
            p_addcfltcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_addcfltcLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_manage)
                .addContainerGap())
        );

        p_sidepanel.add(p_addcfltc);
        p_addcfltc.setBounds(0, 0, 250, 50);

        p_monitorcfltc.setBackground(new java.awt.Color(46, 49, 49));
        p_monitorcfltc.setForeground(new java.awt.Color(46, 49, 49));
        p_monitorcfltc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_monitorcfltc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_monitorcfltcMouseClicked(evt);
            }
        });

        l_healthworkers.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_healthworkers.setForeground(new java.awt.Color(255, 255, 255));
        l_healthworkers.setText("Monitor ");

        javax.swing.GroupLayout p_monitorcfltcLayout = new javax.swing.GroupLayout(p_monitorcfltc);
        p_monitorcfltc.setLayout(p_monitorcfltcLayout);
        p_monitorcfltcLayout.setHorizontalGroup(
            p_monitorcfltcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_monitorcfltcLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(l_healthworkers)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        p_monitorcfltcLayout.setVerticalGroup(
            p_monitorcfltcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_monitorcfltcLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_healthworkers)
                .addContainerGap())
        );

        p_sidepanel.add(p_monitorcfltc);
        p_monitorcfltc.setBounds(0, 50, 250, 49);

        p_removecfltc.setBackground(new java.awt.Color(46, 49, 49));
        p_removecfltc.setForeground(new java.awt.Color(46, 49, 49));
        p_removecfltc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_removecfltc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_removecfltcMouseClicked(evt);
            }
        });

        l_cfltcs.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_cfltcs.setForeground(new java.awt.Color(255, 255, 255));
        l_cfltcs.setText("Remove ");

        javax.swing.GroupLayout p_removecfltcLayout = new javax.swing.GroupLayout(p_removecfltc);
        p_removecfltc.setLayout(p_removecfltcLayout);
        p_removecfltcLayout.setHorizontalGroup(
            p_removecfltcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_removecfltcLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(l_cfltcs)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        p_removecfltcLayout.setVerticalGroup(
            p_removecfltcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_removecfltcLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_cfltcs)
                .addContainerGap())
        );

        p_sidepanel.add(p_removecfltc);
        p_removecfltc.setBounds(0, 100, 250, 50);

        p_testingcenters.setBackground(new java.awt.Color(46, 49, 49));
        p_testingcenters.setForeground(new java.awt.Color(46, 49, 49));

        p_updatechart.setBackground(new java.awt.Color(46, 49, 49));
        p_updatechart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_updatechart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_updatechartMouseClicked(evt);
            }
        });

        l_hotspots1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_hotspots1.setForeground(new java.awt.Color(255, 255, 255));
        l_hotspots1.setText("Refresh Chart");

        javax.swing.GroupLayout p_updatechartLayout = new javax.swing.GroupLayout(p_updatechart);
        p_updatechart.setLayout(p_updatechartLayout);
        p_updatechartLayout.setHorizontalGroup(
            p_updatechartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_updatechartLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(l_hotspots1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        p_updatechartLayout.setVerticalGroup(
            p_updatechartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_updatechartLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(l_hotspots1)
                .addContainerGap())
        );

        javax.swing.GroupLayout p_testingcentersLayout = new javax.swing.GroupLayout(p_testingcenters);
        p_testingcenters.setLayout(p_testingcentersLayout);
        p_testingcentersLayout.setHorizontalGroup(
            p_testingcentersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_testingcentersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(p_updatechart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p_testingcentersLayout.setVerticalGroup(
            p_testingcentersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_testingcentersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(p_updatechart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_sidepanel.add(p_testingcenters);
        p_testingcenters.setBounds(0, 200, 250, 50);

        jPanel12.setBackground(new java.awt.Color(46, 49, 49));
        jPanel12.setForeground(new java.awt.Color(46, 49, 49));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        p_sidepanel.add(jPanel12);
        jPanel12.setBounds(0, 250, 250, 57);

        jPanel15.setBackground(new java.awt.Color(46, 49, 49));
        jPanel15.setForeground(new java.awt.Color(46, 49, 49));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        p_sidepanel.add(jPanel15);
        jPanel15.setBounds(0, 300, 250, 50);

        jPanel14.setBackground(new java.awt.Color(46, 49, 49));
        jPanel14.setForeground(new java.awt.Color(46, 49, 49));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        p_sidepanel.add(jPanel14);
        jPanel14.setBounds(0, 350, 250, 50);

        jPanel16.setBackground(new java.awt.Color(46, 49, 49));
        jPanel16.setForeground(new java.awt.Color(46, 49, 49));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        p_sidepanel.add(jPanel16);
        jPanel16.setBounds(0, 400, 250, 50);

        jPanel17.setBackground(new java.awt.Color(46, 49, 49));
        jPanel17.setForeground(new java.awt.Color(46, 49, 49));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        p_sidepanel.add(jPanel17);
        jPanel17.setBounds(0, 450, 250, 50);

        p_contactcfltc.setBackground(new java.awt.Color(46, 49, 49));
        p_contactcfltc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_contactcfltc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_contactcfltcMouseClicked(evt);
            }
        });

        l_hotspots.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_hotspots.setForeground(new java.awt.Color(255, 255, 255));
        l_hotspots.setText("Contact");

        javax.swing.GroupLayout p_contactcfltcLayout = new javax.swing.GroupLayout(p_contactcfltc);
        p_contactcfltc.setLayout(p_contactcfltcLayout);
        p_contactcfltcLayout.setHorizontalGroup(
            p_contactcfltcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_contactcfltcLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(l_hotspots, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        p_contactcfltcLayout.setVerticalGroup(
            p_contactcfltcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_contactcfltcLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(l_hotspots)
                .addContainerGap())
        );

        p_sidepanel.add(p_contactcfltc);
        p_contactcfltc.setBounds(0, 150, 250, 50);

        getContentPane().add(p_sidepanel);
        p_sidepanel.setBounds(0, 60, 250, 1260);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1);
        jPanel1.setBounds(250, 60, 660, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p_addcfltcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addcfltcMouseClicked
        // TODO add your handling code here:
        new AddCFLTC().setVisible(true);
    }//GEN-LAST:event_p_addcfltcMouseClicked

    private void p_monitorcfltcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_monitorcfltcMouseClicked
        // TODO add your handling code here:
        new monitorcfltc().setVisible(true);
    }//GEN-LAST:event_p_monitorcfltcMouseClicked

    private void p_removecfltcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_removecfltcMouseClicked
        // TODO add your handling code here:
         new Removecfltc().setVisible(true);
    }//GEN-LAST:event_p_removecfltcMouseClicked

    private void p_contactcfltcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_contactcfltcMouseClicked
        // TODO add your handling code here:
        new ContactCFLTC().setVisible(true);
    }//GEN-LAST:event_p_contactcfltcMouseClicked

    private void img_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_backMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_img_backMouseClicked

    private void p_updatechartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_updatechartMouseClicked
        // TODO add your handling code here:
        fetch();
        JOptionPane.showMessageDialog(null,"Chart Refreshed");

    }//GEN-LAST:event_p_updatechartMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CFLTCs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CFLTCs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CFLTCs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CFLTCs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CFLTCs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img_back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JLabel l_cfltcs;
    private javax.swing.JLabel l_healthworkers;
    private javax.swing.JLabel l_hotspots;
    private javax.swing.JLabel l_hotspots1;
    private javax.swing.JLabel l_manage;
    private javax.swing.JLabel l_results1;
    private javax.swing.JPanel p_addcfltc;
    private javax.swing.JPanel p_contactcfltc;
    private javax.swing.JPanel p_monitorcfltc;
    private javax.swing.JPanel p_refresh_chart;
    private javax.swing.JPanel p_removecfltc;
    private javax.swing.JPanel p_sidepanel;
    private javax.swing.JPanel p_testingcenters;
    private javax.swing.JLabel p_title;
    private javax.swing.JPanel p_toppanel;
    private javax.swing.JPanel p_updatechart;
    // End of variables declaration//GEN-END:variables
}
