/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asdtemp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author ajayj
 */
public class CitizenDash extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public CitizenDash(String name,int key) {
        username=name;
        id=key;
        initComponents();
        this.setLocationRelativeTo(null);
        l_username.setText(username);
        fetch();
    }
    private void fetch()
    {
         try
    {
        Connection con=new Connector().getCon();
        PreparedStatement ps=con.prepareStatement("SELECT c_covid_status FROM asdproject.citizen_list WHERE c_id=?");
        ps.setString(1,Integer.toString(id));
        ResultSet rs=ps.executeQuery();
        if(rs.next())
        l_status.setText(rs.getString(1));
        ps=con.prepareStatement("SELECT count(c_covid_status) FROM asdproject.citizen_list WHERE c_covid_status='Died';");
         rs=ps.executeQuery();
        if(rs.next())
        l_death_count.setText(rs.getString(1));
        ps=con.prepareStatement("SELECT count(c_covid_status) FROM asdproject.citizen_list WHERE c_covid_status='Positive';");
         rs=ps.executeQuery();
        if(rs.next())
        l_active_count.setText(rs.getString(1));
        ps=con.prepareStatement("SELECT count(sl_num) FROM asdproject.total_recoverd_list;");
         rs=ps.executeQuery();
        if(rs.next())
        l_recovered_count.setText(rs.getString(1));
        ps=con.prepareStatement("SELECT count(sl_no) FROM asdproject.total_affected_list;");
         rs=ps.executeQuery();
        if(rs.next())
        l_affected_count.setText(rs.getString(1));
    }
        catch(ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null,"Class Error. Contact System Admin");
        } catch(SQLException e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Unknown Error. Contact System Admin");
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_sidepanel = new javax.swing.JPanel();
        p_testing_centers = new javax.swing.JPanel();
        l_overallstatistics = new javax.swing.JLabel();
        p_hotspots = new javax.swing.JPanel();
        l_hotspots = new javax.swing.JLabel();
        p_cfltcs = new javax.swing.JPanel();
        l_cfltcs = new javax.swing.JLabel();
        p_applyhealthworker = new javax.swing.JPanel();
        l_applyhealthworker = new javax.swing.JLabel();
        p_checksymptoms = new javax.swing.JPanel();
        l_checksymptoms = new javax.swing.JLabel();
        sep_applyheallth_checksym = new javax.swing.JSeparator();
        p_govtorders = new javax.swing.JPanel();
        l_govtorders = new javax.swing.JLabel();
        p_covidawareness = new javax.swing.JPanel();
        l_covidawareness = new javax.swing.JLabel();
        p_impcontacts = new javax.swing.JPanel();
        l_impcontacts = new javax.swing.JLabel();
        p_faqs = new javax.swing.JPanel();
        l_faqs = new javax.swing.JLabel();
        p_applyvolunteer = new javax.swing.JPanel();
        sep_cfltc_applyvol = new javax.swing.JSeparator();
        l_applyvolunteer = new javax.swing.JLabel();
        p_applyvolunteer1 = new javax.swing.JPanel();
        sep_cfltc_applyvol1 = new javax.swing.JSeparator();
        l_applyvolunteer1 = new javax.swing.JLabel();
        p_myinbox = new javax.swing.JPanel();
        l_impcontacts1 = new javax.swing.JLabel();
        p_toppanel = new javax.swing.JPanel();
        p_userpanel = new javax.swing.JPanel();
        img_user = new javax.swing.JLabel();
        cb_useroptions = new javax.swing.JComboBox<>();
        l_username = new javax.swing.JLabel();
        l_designation = new javax.swing.JLabel();
        p_title = new javax.swing.JLabel();
        img_virus = new javax.swing.JLabel();
        p_mainpanel = new javax.swing.JPanel();
        l_welcomenote = new javax.swing.JLabel();
        l_status = new javax.swing.JLabel();
        p_totconfirmed = new javax.swing.JPanel();
        l_totconfirmed = new javax.swing.JLabel();
        l_affected_count = new javax.swing.JLabel();
        p_recovered = new javax.swing.JPanel();
        l_recovered_count = new javax.swing.JLabel();
        l_recovered = new javax.swing.JLabel();
        p_deaths = new javax.swing.JPanel();
        l_death_count = new javax.swing.JLabel();
        l_deaths = new javax.swing.JLabel();
        p_activecases = new javax.swing.JPanel();
        l_activecases = new javax.swing.JLabel();
        l_active_count = new javax.swing.JLabel();
        b_refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        p_sidepanel.setBackground(new java.awt.Color(46, 49, 49));
        p_sidepanel.setToolTipText("");
        p_sidepanel.setLayout(null);

        p_testing_centers.setBackground(new java.awt.Color(46, 49, 49));
        p_testing_centers.setForeground(new java.awt.Color(46, 49, 49));
        p_testing_centers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_testing_centers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_testing_centersMouseClicked(evt);
            }
        });

        l_overallstatistics.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_overallstatistics.setForeground(new java.awt.Color(255, 255, 255));
        l_overallstatistics.setText("Testing Centers");

        javax.swing.GroupLayout p_testing_centersLayout = new javax.swing.GroupLayout(p_testing_centers);
        p_testing_centers.setLayout(p_testing_centersLayout);
        p_testing_centersLayout.setHorizontalGroup(
            p_testing_centersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_testing_centersLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(l_overallstatistics)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        p_testing_centersLayout.setVerticalGroup(
            p_testing_centersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_testing_centersLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_overallstatistics)
                .addContainerGap())
        );

        p_sidepanel.add(p_testing_centers);
        p_testing_centers.setBounds(0, 0, 250, 50);

        p_hotspots.setBackground(new java.awt.Color(46, 49, 49));
        p_hotspots.setForeground(new java.awt.Color(46, 49, 49));
        p_hotspots.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_hotspots.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_hotspotsMouseClicked(evt);
            }
        });

        l_hotspots.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_hotspots.setForeground(new java.awt.Color(255, 255, 255));
        l_hotspots.setText("Hotspots");

        javax.swing.GroupLayout p_hotspotsLayout = new javax.swing.GroupLayout(p_hotspots);
        p_hotspots.setLayout(p_hotspotsLayout);
        p_hotspotsLayout.setHorizontalGroup(
            p_hotspotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hotspotsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(l_hotspots)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        p_hotspotsLayout.setVerticalGroup(
            p_hotspotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_hotspotsLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_hotspots)
                .addContainerGap())
        );

        p_sidepanel.add(p_hotspots);
        p_hotspots.setBounds(0, 50, 250, 49);

        p_cfltcs.setBackground(new java.awt.Color(46, 49, 49));
        p_cfltcs.setForeground(new java.awt.Color(46, 49, 49));
        p_cfltcs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_cfltcs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_cfltcsMouseClicked(evt);
            }
        });

        l_cfltcs.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_cfltcs.setForeground(new java.awt.Color(255, 255, 255));
        l_cfltcs.setText("CFLTCs");

        javax.swing.GroupLayout p_cfltcsLayout = new javax.swing.GroupLayout(p_cfltcs);
        p_cfltcs.setLayout(p_cfltcsLayout);
        p_cfltcsLayout.setHorizontalGroup(
            p_cfltcsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_cfltcsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(l_cfltcs)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        p_cfltcsLayout.setVerticalGroup(
            p_cfltcsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_cfltcsLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_cfltcs)
                .addContainerGap())
        );

        p_sidepanel.add(p_cfltcs);
        p_cfltcs.setBounds(0, 100, 250, 50);

        p_applyhealthworker.setBackground(new java.awt.Color(46, 49, 49));
        p_applyhealthworker.setForeground(new java.awt.Color(46, 49, 49));
        p_applyhealthworker.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_applyhealthworker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_applyhealthworkerMouseClicked(evt);
            }
        });

        l_applyhealthworker.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_applyhealthworker.setForeground(new java.awt.Color(255, 255, 255));
        l_applyhealthworker.setText("Apply as Healthworker");

        javax.swing.GroupLayout p_applyhealthworkerLayout = new javax.swing.GroupLayout(p_applyhealthworker);
        p_applyhealthworker.setLayout(p_applyhealthworkerLayout);
        p_applyhealthworkerLayout.setHorizontalGroup(
            p_applyhealthworkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_applyhealthworkerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(l_applyhealthworker)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        p_applyhealthworkerLayout.setVerticalGroup(
            p_applyhealthworkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_applyhealthworkerLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_applyhealthworker)
                .addContainerGap())
        );

        p_sidepanel.add(p_applyhealthworker);
        p_applyhealthworker.setBounds(0, 200, 250, 49);

        p_checksymptoms.setBackground(new java.awt.Color(46, 49, 49));
        p_checksymptoms.setForeground(new java.awt.Color(46, 49, 49));
        p_checksymptoms.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_checksymptoms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_checksymptomsMouseClicked(evt);
            }
        });

        l_checksymptoms.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_checksymptoms.setForeground(new java.awt.Color(255, 255, 255));
        l_checksymptoms.setText("Check Symptoms");

        javax.swing.GroupLayout p_checksymptomsLayout = new javax.swing.GroupLayout(p_checksymptoms);
        p_checksymptoms.setLayout(p_checksymptomsLayout);
        p_checksymptomsLayout.setHorizontalGroup(
            p_checksymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_checksymptomsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(p_checksymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_checksymptoms)
                    .addComponent(sep_applyheallth_checksym, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        p_checksymptomsLayout.setVerticalGroup(
            p_checksymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_checksymptomsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sep_applyheallth_checksym, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_checksymptoms)
                .addContainerGap())
        );

        p_sidepanel.add(p_checksymptoms);
        p_checksymptoms.setBounds(0, 250, 250, 55);

        p_govtorders.setBackground(new java.awt.Color(46, 49, 49));
        p_govtorders.setForeground(new java.awt.Color(46, 49, 49));
        p_govtorders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_govtorders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_govtordersMouseClicked(evt);
            }
        });

        l_govtorders.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_govtorders.setForeground(new java.awt.Color(255, 255, 255));
        l_govtorders.setText("Government Orders");

        javax.swing.GroupLayout p_govtordersLayout = new javax.swing.GroupLayout(p_govtorders);
        p_govtorders.setLayout(p_govtordersLayout);
        p_govtordersLayout.setHorizontalGroup(
            p_govtordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_govtordersLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(l_govtorders)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        p_govtordersLayout.setVerticalGroup(
            p_govtordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_govtordersLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_govtorders)
                .addContainerGap())
        );

        p_sidepanel.add(p_govtorders);
        p_govtorders.setBounds(0, 300, 250, 49);

        p_covidawareness.setBackground(new java.awt.Color(46, 49, 49));
        p_covidawareness.setForeground(new java.awt.Color(46, 49, 49));
        p_covidawareness.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_covidawareness.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_covidawarenessMouseClicked(evt);
            }
        });

        l_covidawareness.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_covidawareness.setForeground(new java.awt.Color(255, 255, 255));
        l_covidawareness.setText("Covid Awareness");

        javax.swing.GroupLayout p_covidawarenessLayout = new javax.swing.GroupLayout(p_covidawareness);
        p_covidawareness.setLayout(p_covidawarenessLayout);
        p_covidawarenessLayout.setHorizontalGroup(
            p_covidawarenessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_covidawarenessLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(l_covidawareness)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        p_covidawarenessLayout.setVerticalGroup(
            p_covidawarenessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_covidawarenessLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_covidawareness)
                .addContainerGap())
        );

        p_sidepanel.add(p_covidawareness);
        p_covidawareness.setBounds(0, 350, 250, 49);

        p_impcontacts.setBackground(new java.awt.Color(46, 49, 49));
        p_impcontacts.setForeground(new java.awt.Color(46, 49, 49));
        p_impcontacts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_impcontacts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_impcontactsMouseClicked(evt);
            }
        });

        l_impcontacts.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_impcontacts.setForeground(new java.awt.Color(255, 255, 255));
        l_impcontacts.setText("Important Contacts");

        javax.swing.GroupLayout p_impcontactsLayout = new javax.swing.GroupLayout(p_impcontacts);
        p_impcontacts.setLayout(p_impcontactsLayout);
        p_impcontactsLayout.setHorizontalGroup(
            p_impcontactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_impcontactsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(l_impcontacts)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        p_impcontactsLayout.setVerticalGroup(
            p_impcontactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_impcontactsLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_impcontacts)
                .addContainerGap())
        );

        p_sidepanel.add(p_impcontacts);
        p_impcontacts.setBounds(0, 400, 250, 49);

        p_faqs.setBackground(new java.awt.Color(46, 49, 49));
        p_faqs.setForeground(new java.awt.Color(46, 49, 49));
        p_faqs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_faqs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_faqsMouseClicked(evt);
            }
        });

        l_faqs.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_faqs.setForeground(new java.awt.Color(255, 255, 255));
        l_faqs.setText("FAQs");

        javax.swing.GroupLayout p_faqsLayout = new javax.swing.GroupLayout(p_faqs);
        p_faqs.setLayout(p_faqsLayout);
        p_faqsLayout.setHorizontalGroup(
            p_faqsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_faqsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(l_faqs)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        p_faqsLayout.setVerticalGroup(
            p_faqsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_faqsLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_faqs)
                .addContainerGap())
        );

        p_sidepanel.add(p_faqs);
        p_faqs.setBounds(0, 450, 250, 49);

        p_applyvolunteer.setBackground(new java.awt.Color(46, 49, 49));
        p_applyvolunteer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_applyvolunteer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_applyvolunteerMouseClicked(evt);
            }
        });

        l_applyvolunteer.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_applyvolunteer.setForeground(new java.awt.Color(255, 255, 255));
        l_applyvolunteer.setText("Apply as Volunteer");

        javax.swing.GroupLayout p_applyvolunteerLayout = new javax.swing.GroupLayout(p_applyvolunteer);
        p_applyvolunteer.setLayout(p_applyvolunteerLayout);
        p_applyvolunteerLayout.setHorizontalGroup(
            p_applyvolunteerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_applyvolunteerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(p_applyvolunteerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_applyvolunteer, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sep_cfltc_applyvol, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(328, 328, 328))
        );
        p_applyvolunteerLayout.setVerticalGroup(
            p_applyvolunteerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_applyvolunteerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sep_cfltc_applyvol, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_applyvolunteer)
                .addContainerGap())
        );

        p_sidepanel.add(p_applyvolunteer);
        p_applyvolunteer.setBounds(0, 150, 250, 50);

        p_applyvolunteer1.setBackground(new java.awt.Color(46, 49, 49));
        p_applyvolunteer1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_applyvolunteer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_applyvolunteer1MouseClicked(evt);
            }
        });

        l_applyvolunteer1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_applyvolunteer1.setForeground(new java.awt.Color(255, 255, 255));
        l_applyvolunteer1.setText("My Covid Data");

        javax.swing.GroupLayout p_applyvolunteer1Layout = new javax.swing.GroupLayout(p_applyvolunteer1);
        p_applyvolunteer1.setLayout(p_applyvolunteer1Layout);
        p_applyvolunteer1Layout.setHorizontalGroup(
            p_applyvolunteer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_applyvolunteer1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(p_applyvolunteer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_applyvolunteer1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sep_cfltc_applyvol1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(328, 328, 328))
        );
        p_applyvolunteer1Layout.setVerticalGroup(
            p_applyvolunteer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_applyvolunteer1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sep_cfltc_applyvol1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_applyvolunteer1)
                .addGap(6, 6, 6))
        );

        p_sidepanel.add(p_applyvolunteer1);
        p_applyvolunteer1.setBounds(0, 500, 250, 50);

        p_myinbox.setBackground(new java.awt.Color(46, 49, 49));
        p_myinbox.setForeground(new java.awt.Color(46, 49, 49));
        p_myinbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_myinbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_myinboxMouseClicked(evt);
            }
        });

        l_impcontacts1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_impcontacts1.setForeground(new java.awt.Color(255, 255, 255));
        l_impcontacts1.setText("My Inbox");

        javax.swing.GroupLayout p_myinboxLayout = new javax.swing.GroupLayout(p_myinbox);
        p_myinbox.setLayout(p_myinboxLayout);
        p_myinboxLayout.setHorizontalGroup(
            p_myinboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_myinboxLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(l_impcontacts1)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        p_myinboxLayout.setVerticalGroup(
            p_myinboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_myinboxLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_impcontacts1)
                .addContainerGap())
        );

        p_sidepanel.add(p_myinbox);
        p_myinbox.setBounds(0, 560, 250, 49);

        p_toppanel.setBackground(new java.awt.Color(255, 255, 255));

        p_userpanel.setBackground(new java.awt.Color(46, 49, 49));
        p_userpanel.setForeground(new java.awt.Color(46, 49, 49));
        p_userpanel.setLayout(null);

        img_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/50x50.png"))); // NOI18N
        img_user.setText("jLabel12");
        p_userpanel.add(img_user);
        img_user.setBounds(10, 0, 50, 60);

        cb_useroptions.setBackground(new java.awt.Color(46, 49, 49));
        cb_useroptions.setForeground(new java.awt.Color(46, 49, 49));
        cb_useroptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Home", "Edit Profile", "Logout" }));
        cb_useroptions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb_useroptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_useroptionsActionPerformed(evt);
            }
        });
        p_userpanel.add(cb_useroptions);
        cb_useroptions.setBounds(140, 40, 110, 19);

        l_username.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_username.setForeground(new java.awt.Color(255, 255, 255));
        l_username.setText("User Name");
        p_userpanel.add(l_username);
        l_username.setBounds(70, 10, 160, 19);

        l_designation.setForeground(new java.awt.Color(255, 255, 255));
        l_designation.setText("Citizen");
        p_userpanel.add(l_designation);
        l_designation.setBounds(70, 30, 60, 30);

        p_title.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        p_title.setText("Kerala : Covid Analysis");

        img_virus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/vir_60x60.png"))); // NOI18N
        img_virus.setText("jLabel22");

        javax.swing.GroupLayout p_toppanelLayout = new javax.swing.GroupLayout(p_toppanel);
        p_toppanel.setLayout(p_toppanelLayout);
        p_toppanelLayout.setHorizontalGroup(
            p_toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_toppanelLayout.createSequentialGroup()
                .addComponent(p_userpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(img_virus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_title)
                .addContainerGap(336, Short.MAX_VALUE))
        );
        p_toppanelLayout.setVerticalGroup(
            p_toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_userpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_toppanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_title)
                .addGap(41, 41, 41))
            .addGroup(p_toppanelLayout.createSequentialGroup()
                .addComponent(img_virus)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        p_mainpanel.setBackground(new java.awt.Color(232, 236, 241));

        l_welcomenote.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        l_welcomenote.setText("My Covid Status : ");

        l_status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l_status.setText("Not Affected");

        p_totconfirmed.setBackground(new java.awt.Color(220, 53, 69));

        l_totconfirmed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_totconfirmed.setForeground(new java.awt.Color(255, 255, 255));
        l_totconfirmed.setText("Total Affected");

        l_affected_count.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        l_affected_count.setForeground(new java.awt.Color(255, 255, 255));
        l_affected_count.setText("0");

        javax.swing.GroupLayout p_totconfirmedLayout = new javax.swing.GroupLayout(p_totconfirmed);
        p_totconfirmed.setLayout(p_totconfirmedLayout);
        p_totconfirmedLayout.setHorizontalGroup(
            p_totconfirmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_totconfirmedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_totconfirmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_affected_count)
                    .addComponent(l_totconfirmed))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        p_totconfirmedLayout.setVerticalGroup(
            p_totconfirmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_totconfirmedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_affected_count)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_totconfirmed)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        p_recovered.setBackground(new java.awt.Color(40, 167, 69));

        l_recovered_count.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        l_recovered_count.setForeground(new java.awt.Color(255, 255, 255));
        l_recovered_count.setText("0");

        l_recovered.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_recovered.setForeground(new java.awt.Color(255, 255, 255));
        l_recovered.setText("Total Recovered");

        javax.swing.GroupLayout p_recoveredLayout = new javax.swing.GroupLayout(p_recovered);
        p_recovered.setLayout(p_recoveredLayout);
        p_recoveredLayout.setHorizontalGroup(
            p_recoveredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_recoveredLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_recoveredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_recovered_count)
                    .addComponent(l_recovered))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        p_recoveredLayout.setVerticalGroup(
            p_recoveredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_recoveredLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_recovered_count)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_recovered)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        p_deaths.setBackground(new java.awt.Color(23, 162, 184));

        l_death_count.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        l_death_count.setForeground(new java.awt.Color(255, 255, 255));
        l_death_count.setText("0");

        l_deaths.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_deaths.setForeground(new java.awt.Color(255, 255, 255));
        l_deaths.setText("Total Deaths");

        javax.swing.GroupLayout p_deathsLayout = new javax.swing.GroupLayout(p_deaths);
        p_deaths.setLayout(p_deathsLayout);
        p_deathsLayout.setHorizontalGroup(
            p_deathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_deathsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_deathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_death_count)
                    .addComponent(l_deaths))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_deathsLayout.setVerticalGroup(
            p_deathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_deathsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_death_count)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_deaths)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        p_activecases.setBackground(new java.awt.Color(255, 193, 7));

        l_activecases.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_activecases.setForeground(new java.awt.Color(255, 255, 255));
        l_activecases.setText("Active Cases");

        l_active_count.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        l_active_count.setForeground(new java.awt.Color(255, 255, 255));
        l_active_count.setText("0");

        javax.swing.GroupLayout p_activecasesLayout = new javax.swing.GroupLayout(p_activecases);
        p_activecases.setLayout(p_activecasesLayout);
        p_activecasesLayout.setHorizontalGroup(
            p_activecasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_activecasesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_activecasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_active_count)
                    .addComponent(l_activecases))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        p_activecasesLayout.setVerticalGroup(
            p_activecasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_activecasesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_active_count)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_activecases)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        b_refresh.setBackground(new java.awt.Color(46, 49, 49));
        b_refresh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b_refresh.setForeground(new java.awt.Color(255, 255, 255));
        b_refresh.setText("Refresh Statistics");
        b_refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_mainpanelLayout = new javax.swing.GroupLayout(p_mainpanel);
        p_mainpanel.setLayout(p_mainpanelLayout);
        p_mainpanelLayout.setHorizontalGroup(
            p_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_mainpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p_mainpanelLayout.createSequentialGroup()
                        .addComponent(l_welcomenote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_status)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_refresh))
                    .addGroup(p_mainpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(p_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p_activecases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_totconfirmed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(p_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p_deaths, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p_recovered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75))
        );
        p_mainpanelLayout.setVerticalGroup(
            p_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainpanelLayout.createSequentialGroup()
                .addGroup(p_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_mainpanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(p_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_welcomenote, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_status)))
                    .addGroup(p_mainpanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(b_refresh)))
                .addGap(43, 43, 43)
                .addGroup(p_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_totconfirmed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_recovered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(p_mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_activecases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_deaths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(309, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(p_mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_toppanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_sidepanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(p_toppanel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(p_mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_useroptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_useroptionsActionPerformed
        // TODO add your handling code here:
        if(cb_useroptions.getSelectedIndex()==2)
        {
            this.dispose();
            JOptionPane.showMessageDialog(null,"Stay Home Stay Safe !","Logout Success",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(cb_useroptions.getSelectedIndex()==1)
        new myprofile(id).setVisible(true);
        //new Login().setVisible(true);
    }//GEN-LAST:event_cb_useroptionsActionPerformed

    private void p_applyvolunteerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_applyvolunteerMouseClicked
        // TODO add your handling code here:
        try
    {
        Connection con=new Connector().getCon();
        PreparedStatement ps=con.prepareStatement("SELECT * FROM asdproject.volunteer_requests WHERE cit_id=?");
        ps.setString(1,Integer.toString(id));
        ResultSet rs=ps.executeQuery();
        if(rs.next())
        JOptionPane.showMessageDialog(null,"You have already submitted Volunteer Application !!");
        else
            new VolunteerReg(id).setVisible(true);
    }
        catch(ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null,"Class Error. Contact System Admin");
        } catch(SQLException e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Unknown Error. Contact System Admin");
        } 
        
    }//GEN-LAST:event_p_applyvolunteerMouseClicked

    private void p_applyhealthworkerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_applyhealthworkerMouseClicked
        // TODO add your handling code here:
         try
    {
        Connection con=new Connector().getCon();
        PreparedStatement ps=con.prepareStatement("SELECT * FROM asdproject.health_worker_requests WHERE cit_id=?");
        ps.setString(1,Integer.toString(id));
        ResultSet rs=ps.executeQuery();
        if(rs.next())
        JOptionPane.showMessageDialog(null,"You have already submitted Health Worker Application !!");
        else
            new HealthWorkerReg(id).setVisible(true);
    }
        catch(ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null,"Class Error. Contact System Admin");
        } catch(SQLException e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Unknown Error. Contact System Admin");
        } 
        
    }//GEN-LAST:event_p_applyhealthworkerMouseClicked

    private void p_checksymptomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_checksymptomsMouseClicked
        // TODO add your handling code here:
        new symptoms().setVisible(true);
    }//GEN-LAST:event_p_checksymptomsMouseClicked

    private void p_govtordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_govtordersMouseClicked
        // TODO add your handling code here:
        new GovtOrders().setVisible(true);
    }//GEN-LAST:event_p_govtordersMouseClicked

    private void p_covidawarenessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_covidawarenessMouseClicked
        // TODO add your handling code here:
         new CovidAwareness().setVisible(true);
    }//GEN-LAST:event_p_covidawarenessMouseClicked

    private void p_impcontactsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_impcontactsMouseClicked
        // TODO add your handling code here:
        new importantcontact().setVisible(true);
    }//GEN-LAST:event_p_impcontactsMouseClicked

    private void p_faqsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_faqsMouseClicked
        // TODO add your handling code here:
        new FAQ(id).setVisible(true);
    }//GEN-LAST:event_p_faqsMouseClicked

    private void p_applyvolunteer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_applyvolunteer1MouseClicked
        // TODO add your handling code here:
         new MyCovidData(id).setVisible(true);
    }//GEN-LAST:event_p_applyvolunteer1MouseClicked

    private void p_myinboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_myinboxMouseClicked
        // TODO add your handling code here:
        new Messages(id).setVisible(true);
    }//GEN-LAST:event_p_myinboxMouseClicked

    private void p_hotspotsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_hotspotsMouseClicked
        // TODO add your handling code here:
        new hotspot_citizen_dash().setVisible(true);
    }//GEN-LAST:event_p_hotspotsMouseClicked

    private void p_cfltcsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_cfltcsMouseClicked
        // TODO add your handling code here:
        new cfltc_citizen_dash().setVisible(true);
    }//GEN-LAST:event_p_cfltcsMouseClicked

    private void p_testing_centersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_testing_centersMouseClicked
        // TODO add your handling code here:
        new testingcenter_citizen_dash().setVisible(true);
    }//GEN-LAST:event_p_testing_centersMouseClicked

    private void b_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_refreshActionPerformed
        // TODO add your handling code here:
        fetch();
        JOptionPane.showMessageDialog(null,"Values Updated With Latest Data!");
    }//GEN-LAST:event_b_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CitizenDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CitizenDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CitizenDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CitizenDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//    
//         try{
//            for(int i =0; i<4251; i++){
//                Thread.sleep((long) 0.25);
//                CitizenDash.l_confirded_count.setText(Integer.toString(i));
//            }
//            Thread.sleep((long) 0.25);
//            for(int j =0; j<3161; j++){
//                Thread.sleep((long) 0.25);
//                l_recovered_count.setText(Integer.toString(j));
//            }
//            Thread.sleep((long) 0.25);
//            for(int k =0; k<951; k++){
//                Thread.sleep((long) 0.25);
//                l_active_count.setText(Integer.toString(k));
//            }
//            Thread.sleep((long) 0.25);
//            for(int l =0; l<1202; l++){
//                Thread.sleep((long) 0.25);
//                l_death_count.setText(Integer.toString(l));
//            }
//            Thread.sleep((long) 0.25);
//        } catch(Exception e){
//        }
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new CitizenDash().setVisible(true);
////            }
////        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_refresh;
    private javax.swing.JComboBox<String> cb_useroptions;
    private javax.swing.JLabel img_user;
    private javax.swing.JLabel img_virus;
    private javax.swing.JLabel l_active_count;
    private javax.swing.JLabel l_activecases;
    private javax.swing.JLabel l_affected_count;
    private javax.swing.JLabel l_applyhealthworker;
    private javax.swing.JLabel l_applyvolunteer;
    private javax.swing.JLabel l_applyvolunteer1;
    private javax.swing.JLabel l_cfltcs;
    private javax.swing.JLabel l_checksymptoms;
    private javax.swing.JLabel l_covidawareness;
    private javax.swing.JLabel l_death_count;
    private javax.swing.JLabel l_deaths;
    private javax.swing.JLabel l_designation;
    private javax.swing.JLabel l_faqs;
    private javax.swing.JLabel l_govtorders;
    private javax.swing.JLabel l_hotspots;
    private javax.swing.JLabel l_impcontacts;
    private javax.swing.JLabel l_impcontacts1;
    private javax.swing.JLabel l_overallstatistics;
    private javax.swing.JLabel l_recovered;
    private javax.swing.JLabel l_recovered_count;
    private javax.swing.JLabel l_status;
    private javax.swing.JLabel l_totconfirmed;
    private javax.swing.JLabel l_username;
    private javax.swing.JLabel l_welcomenote;
    private javax.swing.JPanel p_activecases;
    private javax.swing.JPanel p_applyhealthworker;
    private javax.swing.JPanel p_applyvolunteer;
    private javax.swing.JPanel p_applyvolunteer1;
    private javax.swing.JPanel p_cfltcs;
    private javax.swing.JPanel p_checksymptoms;
    private javax.swing.JPanel p_covidawareness;
    private javax.swing.JPanel p_deaths;
    private javax.swing.JPanel p_faqs;
    private javax.swing.JPanel p_govtorders;
    private javax.swing.JPanel p_hotspots;
    private javax.swing.JPanel p_impcontacts;
    private javax.swing.JPanel p_mainpanel;
    private javax.swing.JPanel p_myinbox;
    private javax.swing.JPanel p_recovered;
    private javax.swing.JPanel p_sidepanel;
    private javax.swing.JPanel p_testing_centers;
    private javax.swing.JLabel p_title;
    private javax.swing.JPanel p_toppanel;
    private javax.swing.JPanel p_totconfirmed;
    private javax.swing.JPanel p_userpanel;
    private javax.swing.JSeparator sep_applyheallth_checksym;
    private javax.swing.JSeparator sep_cfltc_applyvol;
    private javax.swing.JSeparator sep_cfltc_applyvol1;
    // End of variables declaration//GEN-END:variables
String username;
int flag;
int id;
}
