/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asdtemp;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ajayj
 */
public class FAQ extends javax.swing.JFrame {

    /**
     * Creates new form FAQ
     */
    public FAQ(int k) {
        initComponents();
        this.setLocationRelativeTo(null);
        id=k;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_toppanel = new javax.swing.JPanel();
        l_title = new javax.swing.JLabel();
        img_back = new javax.swing.JLabel();
        p_main = new javax.swing.JPanel();
        p_q1 = new javax.swing.JPanel();
        l_q1 = new javax.swing.JLabel();
        img_q1 = new javax.swing.JLabel();
        p_q2 = new javax.swing.JPanel();
        l_q2 = new javax.swing.JLabel();
        img_q2 = new javax.swing.JLabel();
        p_q3 = new javax.swing.JPanel();
        l_q3 = new javax.swing.JLabel();
        img_q3 = new javax.swing.JLabel();
        p_yourquestion = new javax.swing.JPanel();
        l_yourquestion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_question = new javax.swing.JTextArea();
        b_submit = new javax.swing.JButton();
        l_faq = new javax.swing.JLabel();
        img_faq = new javax.swing.JLabel();
        sp_q1 = new javax.swing.JScrollPane();
        ta_q1ans = new javax.swing.JTextArea();
        sp_q2 = new javax.swing.JScrollPane();
        ta_q2ans = new javax.swing.JTextArea();
        sp_q3 = new javax.swing.JScrollPane();
        ta_q3ans = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(957, 897));
        setResizable(false);
        getContentPane().setLayout(null);

        p_toppanel.setBackground(new java.awt.Color(46, 49, 49));
        p_toppanel.setLayout(null);

        l_title.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        l_title.setForeground(new java.awt.Color(255, 255, 255));
        l_title.setText("FAQs");
        p_toppanel.add(l_title);
        l_title.setBounds(70, 10, 80, 41);

        img_back.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        img_back.setForeground(new java.awt.Color(255, 255, 255));
        img_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/back2.png"))); // NOI18N
        img_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        img_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_backMouseClicked(evt);
            }
        });
        p_toppanel.add(img_back);
        img_back.setBounds(20, 10, 40, 40);

        getContentPane().add(p_toppanel);
        p_toppanel.setBounds(0, 0, 960, 60);

        p_main.setBackground(new java.awt.Color(232, 236, 241));
        p_main.setMinimumSize(new java.awt.Dimension(900, 600));

        p_q1.setBackground(new java.awt.Color(180, 231, 255));

        l_q1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        l_q1.setText("What is corona virus?");

        img_q1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/que.png"))); // NOI18N

        javax.swing.GroupLayout p_q1Layout = new javax.swing.GroupLayout(p_q1);
        p_q1.setLayout(p_q1Layout);
        p_q1Layout.setHorizontalGroup(
            p_q1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_q1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(img_q1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_q1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_q1Layout.setVerticalGroup(
            p_q1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_q1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_q1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_q1)
                    .addComponent(img_q1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_q2.setBackground(new java.awt.Color(180, 231, 255));

        l_q2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        l_q2.setText("What is COVID-19?");

        img_q2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/que.png"))); // NOI18N

        javax.swing.GroupLayout p_q2Layout = new javax.swing.GroupLayout(p_q2);
        p_q2.setLayout(p_q2Layout);
        p_q2Layout.setHorizontalGroup(
            p_q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_q2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(img_q2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_q2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_q2Layout.setVerticalGroup(
            p_q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_q2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p_q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_q2)
                    .addComponent(l_q2)))
        );

        p_q3.setBackground(new java.awt.Color(180, 231, 255));

        l_q3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        l_q3.setText("What are the symptoms of COVID-19");

        img_q3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/que.png"))); // NOI18N

        javax.swing.GroupLayout p_q3Layout = new javax.swing.GroupLayout(p_q3);
        p_q3.setLayout(p_q3Layout);
        p_q3Layout.setHorizontalGroup(
            p_q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_q3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(img_q3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_q3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_q3Layout.setVerticalGroup(
            p_q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_q3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p_q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_q3)
                    .addComponent(l_q3))
                .addContainerGap())
        );

        l_yourquestion.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        l_yourquestion.setText("Having any Queries? Write your question here.");

        javax.swing.GroupLayout p_yourquestionLayout = new javax.swing.GroupLayout(p_yourquestion);
        p_yourquestion.setLayout(p_yourquestionLayout);
        p_yourquestionLayout.setHorizontalGroup(
            p_yourquestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_yourquestionLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(l_yourquestion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_yourquestionLayout.setVerticalGroup(
            p_yourquestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_yourquestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_yourquestion)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        ta_question.setColumns(20);
        ta_question.setLineWrap(true);
        ta_question.setRows(5);
        jScrollPane1.setViewportView(ta_question);

        b_submit.setBackground(new java.awt.Color(0, 102, 0));
        b_submit.setForeground(new java.awt.Color(255, 255, 255));
        b_submit.setText("Submit Query");
        b_submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_submitActionPerformed(evt);
            }
        });

        l_faq.setBackground(new java.awt.Color(0, 0, 0));
        l_faq.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        l_faq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/faq.png"))); // NOI18N
        l_faq.setText("Frequently Asked Questions");

        ta_q1ans.setEditable(false);
        ta_q1ans.setBackground(new java.awt.Color(255, 251, 218));
        ta_q1ans.setColumns(20);
        ta_q1ans.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ta_q1ans.setLineWrap(true);
        ta_q1ans.setRows(5);
        ta_q1ans.setText("COVID-19 is the infectious disease caused by the most recently discovered corona virus. This new virus and disease were unknown before the outbreak began in Wuhan, China, in December 2019.\n");
        sp_q1.setViewportView(ta_q1ans);

        ta_q2ans.setEditable(false);
        ta_q2ans.setBackground(new java.awt.Color(255, 251, 218));
        ta_q2ans.setColumns(20);
        ta_q2ans.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ta_q2ans.setLineWrap(true);
        ta_q2ans.setRows(5);
        ta_q2ans.setText("Corona viruses are a large family of viruses which may cause illness in animals or humans. In humans, several coronaviruses are known to cause respiratory infections ranging from the common cold to more severe diseases such as Middle East Respiratory Syndrome (MERS) and Severe Acute Respiratory Syndrome (SARS). The most recently discovered coronavirus causes coronavirus disease COVID-19.");
        sp_q2.setViewportView(ta_q2ans);

        ta_q3ans.setEditable(false);
        ta_q3ans.setBackground(new java.awt.Color(255, 251, 218));
        ta_q3ans.setColumns(20);
        ta_q3ans.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ta_q3ans.setLineWrap(true);
        ta_q3ans.setRows(5);
        ta_q3ans.setText("The most common symptoms of COVID-19 are fever, tiredness, and dry cough. Some patients may have aches and pains, nasal congestion, runny nose, sore throat or diarrhea. These symptoms are usually mild and begin gradually. Some people become infected but don’t develop any symptoms and don't feel unwell. Most people (about 80%) recover from the disease without needing special treatment. Around 1 out of every 6 people who gets COVID-19 becomes seriously ill and develops difficulty breathing. Older people, and those with underlying medical problems like high blood pressure, heart problems or diabetes, are more likely to develop serious illness. People with fever, cough and difficulty breathing should seek medical attention.");
        sp_q3.setViewportView(ta_q3ans);

        javax.swing.GroupLayout p_mainLayout = new javax.swing.GroupLayout(p_main);
        p_main.setLayout(p_mainLayout);
        p_mainLayout.setHorizontalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sp_q1)
                    .addGroup(p_mainLayout.createSequentialGroup()
                        .addComponent(img_faq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_faq))
                    .addComponent(sp_q3, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                    .addComponent(sp_q2, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                    .addComponent(p_yourquestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(p_q1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_q2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_q3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_mainLayout.createSequentialGroup()
                .addContainerGap(424, Short.MAX_VALUE)
                .addComponent(b_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(420, 420, 420))
        );
        p_mainLayout.setVerticalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_faq)
                    .addComponent(l_faq))
                .addGap(32, 32, 32)
                .addComponent(p_q1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp_q2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p_q2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp_q1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p_q3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp_q3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p_yourquestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_submit)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(p_main);
        p_main.setBounds(0, 60, 960, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_submitActionPerformed
        // TODO add your handling code here: try
    try {
        Connection con=new Connector().getCon();
        PreparedStatement ps=con.prepareStatement("INSERT INTO `asdproject`.`user_query` (`user_id`, `query`) VALUES (?, ?);");
        ps.setString(1,Integer.toString(id));
        ps.setString(2, ta_question.getText());
        int rs=ps.executeUpdate();
        if(rs>0)
        {
        JOptionPane.showMessageDialog(null,"Query Submitted Successfully");
        ta_question.setText("");
        }
        
    }
        catch(ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null,"Class Error. Contact System Admin");
        } catch(SQLException e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Unknown Error. Contact System Admin");
        } 
        
    }//GEN-LAST:event_b_submitActionPerformed

    private void img_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_backMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_img_backMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FAQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FAQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FAQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FAQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FAQ().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_submit;
    private javax.swing.JLabel img_back;
    private javax.swing.JLabel img_faq;
    private javax.swing.JLabel img_q1;
    private javax.swing.JLabel img_q2;
    private javax.swing.JLabel img_q3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_faq;
    private javax.swing.JLabel l_q1;
    private javax.swing.JLabel l_q2;
    private javax.swing.JLabel l_q3;
    private javax.swing.JLabel l_title;
    private javax.swing.JLabel l_yourquestion;
    private javax.swing.JPanel p_main;
    private javax.swing.JPanel p_q1;
    private javax.swing.JPanel p_q2;
    private javax.swing.JPanel p_q3;
    private javax.swing.JPanel p_toppanel;
    private javax.swing.JPanel p_yourquestion;
    private javax.swing.JScrollPane sp_q1;
    private javax.swing.JScrollPane sp_q2;
    private javax.swing.JScrollPane sp_q3;
    private javax.swing.JTextArea ta_q1ans;
    private javax.swing.JTextArea ta_q2ans;
    private javax.swing.JTextArea ta_q3ans;
    private javax.swing.JTextArea ta_question;
    // End of variables declaration//GEN-END:variables
    private int id;
}
