/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asdtemp;

import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.Base64;
/**
 *
 * @author ajayj
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_top = new javax.swing.JPanel();
        l_login = new javax.swing.JLabel();
        l_close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        p_main = new javax.swing.JPanel();
        l_loginas = new javax.swing.JLabel();
        l_userid = new javax.swing.JLabel();
        l_password = new javax.swing.JLabel();
        cb_loginas = new javax.swing.JComboBox<>();
        tf_userid = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        b_login = new javax.swing.JButton();
        b_cancel = new javax.swing.JButton();
        l_register = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 327));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        p_top.setBackground(new java.awt.Color(248, 148, 6));
        p_top.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p_topMousePressed(evt);
            }
        });

        l_login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_login.setForeground(new java.awt.Color(255, 255, 255));
        l_login.setText("Login");

        l_close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_close.setForeground(new java.awt.Color(255, 255, 255));
        l_close.setText("x");
        l_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_closeMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("-");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p_topLayout = new javax.swing.GroupLayout(p_top);
        p_top.setLayout(p_topLayout);
        p_topLayout.setHorizontalGroup(
            p_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_topLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_close, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        p_topLayout.setVerticalGroup(
            p_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_topLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_close)
                        .addComponent(jLabel1))
                    .addComponent(l_login))
                .addContainerGap())
        );

        getContentPane().add(p_top);
        p_top.setBounds(0, 0, 400, 40);

        p_main.setBackground(new java.awt.Color(42, 62, 80));

        l_loginas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_loginas.setForeground(new java.awt.Color(255, 255, 255));
        l_loginas.setText("Login as");

        l_userid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_userid.setForeground(new java.awt.Color(255, 255, 255));
        l_userid.setText("User ID");

        l_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_password.setForeground(new java.awt.Color(255, 255, 255));
        l_password.setText("Password");

        cb_loginas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General Public", "Health Worker", "Volunteer", "Admin" }));
        cb_loginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_loginasActionPerformed(evt);
            }
        });

        tf_userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_useridActionPerformed(evt);
            }
        });

        b_login.setBackground(new java.awt.Color(0, 102, 51));
        b_login.setForeground(new java.awt.Color(255, 255, 255));
        b_login.setText("Login");
        b_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_loginActionPerformed(evt);
            }
        });

        b_cancel.setBackground(new java.awt.Color(255, 0, 0));
        b_cancel.setForeground(new java.awt.Color(255, 255, 255));
        b_cancel.setText("Clear Fields");
        b_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelActionPerformed(evt);
            }
        });

        l_register.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        l_register.setForeground(new java.awt.Color(255, 255, 255));
        l_register.setText("Click here to register");
        l_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_registerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p_mainLayout = new javax.swing.GroupLayout(p_main);
        p_main.setLayout(p_mainLayout);
        p_mainLayout.setHorizontalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainLayout.createSequentialGroup()
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_mainLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_loginas)
                            .addComponent(l_userid)
                            .addComponent(l_password))
                        .addGap(52, 52, 52)
                        .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_loginas, 0, 170, Short.MAX_VALUE)
                            .addComponent(tf_userid)
                            .addComponent(pf_password)))
                    .addGroup(p_mainLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(b_login, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(b_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_mainLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(l_register)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        p_mainLayout.setVerticalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_loginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_loginas))
                .addGap(18, 18, 18)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_userid)
                    .addComponent(tf_userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_password)
                    .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_login)
                    .addComponent(b_cancel))
                .addGap(37, 37, 37)
                .addComponent(l_register)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(p_main);
        p_main.setBounds(0, 40, 400, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_l_closeMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tf_useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_useridActionPerformed
        
    }//GEN-LAST:event_tf_useridActionPerformed

    private void b_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_loginActionPerformed

         try
        {
            String username = tf_userid.getText();
            String password = Base64.getEncoder().encodeToString(new String(pf_password.getPassword()).getBytes());
            int id;
            String usertype=cb_loginas.getSelectedItem().toString();
             con = new Connector().getCon();
            if(usertype.equals("General Public"))
                  stmt=con.prepareStatement("SELECT c_id,c_fullname FROM `asdproject`.`citizen_list` WHERE (`c_user_name`=? and `c_pass`=?);");
            else if(usertype.equals("Volunteer"))
                    stmt=con.prepareStatement("SELECT cit.c_id,cit.c_fullname FROM `asdproject`.`citizen_list` cit, `asdproject`.`volunteer_list` vlist WHERE (cit.`c_user_name`=? and cit.`c_pass`=? and cit.c_id=vlist.citizen_id);");
            
            else if(usertype.equals("Health Worker"))
                    stmt=con.prepareStatement("SELECT cit.c_id,cit.c_fullname FROM `asdproject`.`citizen_list` cit, `asdproject`.`healthworker_list` hwlist WHERE cit.`c_user_name`=? and cit.`c_pass`=? and cit.c_id=hwlist.citizen_id;");
            else
                stmt=con.prepareStatement("SELECT  admin_id, admin_fullname FROM `asdproject`.`admin_list` WHERE admin_username=? AND admin_password=?;");
            stmt.setString(1,username);
            stmt.setString(2,password);
            ResultSet rs=stmt.executeQuery();
            if(rs.next()){
                id=rs.getInt(1);
                tf_userid.setText("");
                pf_password.setText("");
                JOptionPane.showMessageDialog(null,"Welcome "+rs.getString(2),"Login Success",JOptionPane.INFORMATION_MESSAGE);
                if(usertype.equals("General Public"))
                {
                new CitizenDash(rs.getString(2),id).setVisible(true);
                }
                else if(usertype.equals("Health Worker"))
                {
                new HealthWorkerDash(rs.getString(2),id).setVisible(true);
                }
                 else if(usertype.equals("Volunteer"))
                {
                new VolunteerDash(rs.getString(2),id).setVisible(true);
                }
                else
                    new AdminDash(rs.getString(2),id).setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"Username or Password is incorrect. Note that password is case-sensitive","Invalid Credentials",JOptionPane.ERROR_MESSAGE);
                tf_userid.setText("");
                pf_password.setText("");
                
            }
            
        }
        catch(ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null,"Class Error. Contact System Admin");
        } catch(SQLException e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin");
        }
         catch(Exception e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Unknown Error. Contact System Admin");
        
            
        }
    }//GEN-LAST:event_b_loginActionPerformed

    private void cb_loginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_loginasActionPerformed


    }//GEN-LAST:event_cb_loginasActionPerformed

    private void b_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelActionPerformed
        // TODO add your handling code here:
         tf_userid.setText("");
         pf_password.setText("");
    }//GEN-LAST:event_b_cancelActionPerformed

    private void p_topMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_topMousePressed

    }//GEN-LAST:event_p_topMousePressed

    private void l_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_registerMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new register_form().setVisible(true);
    }//GEN-LAST:event_l_registerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cancel;
    private javax.swing.JButton b_login;
    private javax.swing.JComboBox<String> cb_loginas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l_close;
    private javax.swing.JLabel l_login;
    private javax.swing.JLabel l_loginas;
    private javax.swing.JLabel l_password;
    private javax.swing.JLabel l_register;
    private javax.swing.JLabel l_userid;
    private javax.swing.JPanel p_main;
    private javax.swing.JPanel p_top;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextField tf_userid;
    // End of variables declaration//GEN-END:variables
    PreparedStatement stmt;
    Connection con;
}
