/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package asdtemp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ajayj
 */
public class Messages extends javax.swing.JFrame {

    /**
     * Creates new form FAQ
     */
    public Messages(int id) {
        cit_id = id;
        initComponents();
        this.setLocationRelativeTo(null);
        fetch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        l_title = new javax.swing.JLabel();
        img_back = new javax.swing.JLabel();
        p_main = new javax.swing.JPanel();
        l_head1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        t_previousMessageadmin = new javax.swing.JTable();
        l_head2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        t_previousMessagehw = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(46, 49, 49));
        jPanel2.setLayout(null);

        l_title.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        l_title.setForeground(new java.awt.Color(255, 255, 255));
        l_title.setText("Messages");
        jPanel2.add(l_title);
        l_title.setBounds(60, 10, 250, 41);

        img_back.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        img_back.setForeground(new java.awt.Color(255, 255, 255));
        img_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/back2.png"))); // NOI18N
        img_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        img_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_backMouseClicked(evt);
            }
        });
        jPanel2.add(img_back);
        img_back.setBounds(10, 10, 40, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 900, 60);

        p_main.setBackground(new java.awt.Color(232, 236, 241));
        p_main.setMinimumSize(new java.awt.Dimension(900, 700));

        l_head1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        l_head1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/message-icon.png"))); // NOI18N
        l_head1.setText("Messages from Admin");

        t_previousMessageadmin.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        t_previousMessageadmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "From", "Date", "Title", "Message"
            }
        ));
        jScrollPane3.setViewportView(t_previousMessageadmin);

        l_head2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        l_head2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/message-icon.png"))); // NOI18N
        l_head2.setText("Message from Health Workers");

        t_previousMessagehw.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        t_previousMessagehw.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "From", "Date", "Title", "Message"
            }
        ));
        jScrollPane4.setViewportView(t_previousMessagehw);

        javax.swing.GroupLayout p_mainLayout = new javax.swing.GroupLayout(p_main);
        p_main.setLayout(p_mainLayout);
        p_mainLayout.setHorizontalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_mainLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_head1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_head2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        p_mainLayout.setVerticalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(l_head1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(l_head2)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(p_main);
        p_main.setBounds(0, 60, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void img_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_backMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_img_backMouseClicked
    
    private void fetch(){
        
        try{
            con = new Connector().getCon();
            ps = con.prepareStatement("SELECT a.admin_fullname, m.date, m.title, m.message FROM asdproject.admin_list a, asdproject.messages m WHERE a.admin_id=m.mess_from_id AND mess_key=0 AND (m.mess_to_id=? or m.mess_to_id=0);");
            ps.setString(1, Integer.toString(cit_id));
            rs = ps.executeQuery();
            t_previousMessageadmin.setModel(DbUtils.resultSetToTableModel(rs));
            ps = con.prepareStatement("SELECT cl.c_fullname, m.date, m.title, m.message FROM asdproject.citizen_list cl, asdproject.messages m WHERE cl.c_id=m.mess_from_id AND mess_key=1 AND (m.mess_to_id=? or m.mess_to_id=0);");
            ps.setString(1, Integer.toString(cit_id));
            rs = ps.executeQuery();
            t_previousMessagehw.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin");
        }
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Messages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Messages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Messages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Messages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Messages().setVisible(true);
//            }
//        });
//    }
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    
    int id;
    int to_id;
    private int cit_id;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img_back;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel l_head1;
    private javax.swing.JLabel l_head2;
    private javax.swing.JLabel l_title;
    private javax.swing.JPanel p_main;
    private javax.swing.JTable t_previousMessageadmin;
    private javax.swing.JTable t_previousMessagehw;
    // End of variables declaration//GEN-END:variables
}
