/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asdtemp;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Sourav Menon
 */
public class myprofile extends javax.swing.JFrame {

    /**
     * Creates new form register_form
     */
    public myprofile(int u_id) {
        initComponents();
        this.setLocationRelativeTo(null);
        user_id=u_id;
        getdata(user_id);
    }
    
    private void getdata(int id)
    {
        try
        {
            con = new Connector().getCon();
            stmt= con.prepareStatement("SELECT * FROM `asdproject`.`citizen_list` WHERE c_id=?;");
            stmt.setInt(1,id);
            ResultSet rs = stmt.executeQuery();
            if(rs.next())
            {
            tf_fullname.setText(rs.getString(2));
            tf_email.setText(rs.getString(3));
//            tf_username.setText(rs.getString(4));
//            tf_password.setText(rs.getString(5));
            tf_phonenumber.setText(rs.getString(6));
            tf_gender.setText(rs.getString(7));
            tf_blood_group.setText(rs.getString(8));
            tf_dateofbirth.setText(rs.getString(9));
            int d_id=Integer.parseInt(rs.getString(10));
            int bt_id=Integer.parseInt(rs.getString(11));
            int b_id=Integer.parseInt(rs.getString(12));
            tf_wardnumber.setText(rs.getString(13));
            ta_address.setText(rs.getString(14));
            stmt= con.prepareStatement("SELECT dist_name FROM asdproject.districts where dist_id=?;");
            stmt.setInt(1,d_id);
            rs = stmt.executeQuery();
            if(rs.next())
                tf_district.setText(rs.getString(1));
            stmt= con.prepareStatement("SELECT type FROM asdproject.localbodytype where sl_no=?;");
            stmt.setInt(1,bt_id);
            rs = stmt.executeQuery();
            if(rs.next())
                tf_bodytype.setText(rs.getString(1));
            stmt= con.prepareStatement("SELECT p_name FROM asdproject.panchayaths where d_id=? and p_id=?;");
            stmt.setInt(1,d_id);
            stmt.setInt(2,b_id);
            rs = stmt.executeQuery();
            if(rs.next())
                tf_body.setText(rs.getString(1));
            }
        }
        catch(ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null,"Class Error. Contact System Admin");
        } catch(SQLException e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Unknown Error. Contact System Admin");
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        genderset = new javax.swing.ButtonGroup();
        p_regorg = new javax.swing.JPanel();
        l_rname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p_regblu = new javax.swing.JPanel();
        l_fullname = new javax.swing.JLabel();
        tf_fullname = new javax.swing.JTextField();
        tf_dob = new javax.swing.JLabel();
        l_gender = new javax.swing.JLabel();
        l_phone1 = new javax.swing.JLabel();
        l_District = new javax.swing.JLabel();
        l_localbody = new javax.swing.JLabel();
        l_wardnumber = new javax.swing.JLabel();
        l_email = new javax.swing.JLabel();
        t_blood = new javax.swing.JLabel();
        t_address = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_address = new javax.swing.JTextArea();
        l_localbody1 = new javax.swing.JLabel();
        tf_district = new javax.swing.JTextField();
        tf_bodytype = new javax.swing.JTextField();
        tf_dateofbirth = new javax.swing.JTextField();
        tf_gender = new javax.swing.JTextField();
        tf_blood_group = new javax.swing.JTextField();
        tf_body = new javax.swing.JTextField();
        tf_wardnumber = new javax.swing.JTextField();
        tf_phonenumber = new javax.swing.JTextField();
        b_update = new javax.swing.JButton();
        b_changePassword = new javax.swing.JButton();
        b_changeUName = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        p_regorg.setBackground(new java.awt.Color(46, 49, 49));

        l_rname.setBackground(new java.awt.Color(0, 0, 0));
        l_rname.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        l_rname.setForeground(new java.awt.Color(255, 255, 255));
        l_rname.setText("My Profile");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/back2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p_regorgLayout = new javax.swing.GroupLayout(p_regorg);
        p_regorg.setLayout(p_regorgLayout);
        p_regorgLayout.setHorizontalGroup(
            p_regorgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_regorgLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(l_rname)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_regorgLayout.setVerticalGroup(
            p_regorgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_regorgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_regorgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addGroup(p_regorgLayout.createSequentialGroup()
                        .addComponent(l_rname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        p_regblu.setBackground(new java.awt.Color(232, 236, 241));
        p_regblu.setPreferredSize(new java.awt.Dimension(417, 500));

        l_fullname.setBackground(new java.awt.Color(149, 165, 166));
        l_fullname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_fullname.setText("Full Name :");

        tf_fullname.setEditable(false);
        tf_fullname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_fullname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tf_dob.setBackground(new java.awt.Color(149, 165, 166));
        tf_dob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tf_dob.setText("Date of Birth :");

        l_gender.setBackground(new java.awt.Color(149, 165, 166));
        l_gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_gender.setText("Gender");

        l_phone1.setBackground(new java.awt.Color(149, 165, 166));
        l_phone1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_phone1.setText("Phone Number :");

        l_District.setBackground(new java.awt.Color(149, 165, 166));
        l_District.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_District.setText("District :");

        l_localbody.setBackground(new java.awt.Color(149, 165, 166));
        l_localbody.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_localbody.setText("Body type");

        l_wardnumber.setBackground(new java.awt.Color(149, 165, 166));
        l_wardnumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_wardnumber.setText("Ward Number :");

        l_email.setBackground(new java.awt.Color(149, 165, 166));
        l_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_email.setText("Email id :");

        t_blood.setBackground(new java.awt.Color(149, 165, 166));
        t_blood.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t_blood.setText("Blood Group :");

        t_address.setBackground(new java.awt.Color(149, 165, 166));
        t_address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t_address.setText("Address :");

        tf_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });
        tf_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_emailKeyReleased(evt);
            }
        });

        ta_address.setEditable(false);
        ta_address.setColumns(20);
        ta_address.setRows(5);
        jScrollPane1.setViewportView(ta_address);

        l_localbody1.setBackground(new java.awt.Color(149, 165, 166));
        l_localbody1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_localbody1.setText("Body Name");

        tf_district.setEditable(false);
        tf_district.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_district.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_districtActionPerformed(evt);
            }
        });
        tf_district.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_districtKeyReleased(evt);
            }
        });

        tf_bodytype.setEditable(false);
        tf_bodytype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_bodytype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_bodytypeActionPerformed(evt);
            }
        });
        tf_bodytype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_bodytypeKeyReleased(evt);
            }
        });

        tf_dateofbirth.setEditable(false);
        tf_dateofbirth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_dateofbirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dateofbirthActionPerformed(evt);
            }
        });
        tf_dateofbirth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_dateofbirthKeyReleased(evt);
            }
        });

        tf_gender.setEditable(false);
        tf_gender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_genderActionPerformed(evt);
            }
        });
        tf_gender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_genderKeyReleased(evt);
            }
        });

        tf_blood_group.setEditable(false);
        tf_blood_group.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_blood_group.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_blood_groupActionPerformed(evt);
            }
        });
        tf_blood_group.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_blood_groupKeyReleased(evt);
            }
        });

        tf_body.setEditable(false);
        tf_body.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_body.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_bodyActionPerformed(evt);
            }
        });
        tf_body.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_bodyKeyReleased(evt);
            }
        });

        tf_wardnumber.setEditable(false);
        tf_wardnumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_wardnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_wardnumberActionPerformed(evt);
            }
        });
        tf_wardnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_wardnumberKeyReleased(evt);
            }
        });

        tf_phonenumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_phonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_phonenumberActionPerformed(evt);
            }
        });
        tf_phonenumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_phonenumberKeyReleased(evt);
            }
        });

        b_update.setBackground(new java.awt.Color(0, 255, 0));
        b_update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b_update.setText("UPDATE");
        b_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_updateActionPerformed(evt);
            }
        });

        b_changePassword.setBackground(new java.awt.Color(0, 200, 255));
        b_changePassword.setText("Change Password");
        b_changePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_changePasswordActionPerformed(evt);
            }
        });

        b_changeUName.setBackground(new java.awt.Color(0, 200, 255));
        b_changeUName.setText("Change Username");
        b_changeUName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_changeUName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_changeUNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_regbluLayout = new javax.swing.GroupLayout(p_regblu);
        p_regblu.setLayout(p_regbluLayout);
        p_regbluLayout.setHorizontalGroup(
            p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_regbluLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(l_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(tf_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(l_District, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(tf_district, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(p_regbluLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(l_email, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(l_localbody, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(tf_bodytype, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(p_regbluLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(tf_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(tf_dateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(l_localbody1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(tf_body, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(p_regbluLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(l_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(tf_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(l_wardnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(tf_wardnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(p_regbluLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_blood, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_blood_group, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130)
                .addComponent(t_address, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(p_regbluLayout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(b_changePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(p_regbluLayout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(b_changeUName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(p_regbluLayout.createSequentialGroup()
                .addGap(442, 442, 442)
                .addComponent(b_update, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p_regbluLayout.setVerticalGroup(
            p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_regbluLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_regbluLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(tf_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_regbluLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(l_District, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_regbluLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(tf_district, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_regbluLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_localbody, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_regbluLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tf_bodytype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_localbody1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_regbluLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_dateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_wardnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_wardnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_address, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_regbluLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_regbluLayout.createSequentialGroup()
                                .addComponent(t_blood, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(l_phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_regbluLayout.createSequentialGroup()
                                .addComponent(tf_blood_group, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(tf_phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34)
                .addComponent(b_changePassword)
                .addGap(17, 17, 17)
                .addComponent(b_changeUName)
                .addGap(74, 74, 74)
                .addComponent(b_update))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_regorg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(p_regblu, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_regorg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_regblu, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_emailActionPerformed

    private void tf_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_emailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_emailKeyReleased

    private void tf_districtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_districtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_districtActionPerformed

    private void tf_districtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_districtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_districtKeyReleased

    private void tf_bodytypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bodytypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bodytypeActionPerformed

    private void tf_bodytypeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_bodytypeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bodytypeKeyReleased

    private void tf_dateofbirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dateofbirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dateofbirthActionPerformed

    private void tf_dateofbirthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_dateofbirthKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dateofbirthKeyReleased

    private void tf_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_genderActionPerformed

    private void tf_genderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_genderKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_genderKeyReleased

    private void tf_blood_groupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_blood_groupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_blood_groupActionPerformed

    private void tf_blood_groupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_blood_groupKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_blood_groupKeyReleased

    private void tf_bodyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bodyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bodyActionPerformed

    private void tf_bodyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_bodyKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bodyKeyReleased

    private void tf_wardnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_wardnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_wardnumberActionPerformed

    private void tf_wardnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_wardnumberKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_wardnumberKeyReleased

    private void tf_phonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_phonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_phonenumberActionPerformed

    private void tf_phonenumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_phonenumberKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_phonenumberKeyReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void b_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_updateActionPerformed
        // TODO add your handling code here:
        String u_email=tf_email.getText();
 //       String u_pass=tf_password.getText();
        String u_phno=tf_phonenumber.getText();
        String u_address=ta_address.getText();
        try
        {
            con = new Connector().getCon();
            stmt= con.prepareStatement("UPDATE `asdproject`.`citizen_list` SET `c_email` = ?, `c_pass` =?, `c_phno` = ?, `c_address` =? WHERE (`c_id` =?);");
            stmt.setInt(5,user_id);
            stmt.setString(1, u_email);
 //           stmt.setString(2, u_pass);
            stmt.setString(3, u_phno);
            stmt.setString(4, u_address);
            int rs = stmt.executeUpdate();
            if(rs!=0)
            {
                JOptionPane.showMessageDialog(null,"Profile sucessfully updated");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin");
            }
        }
        catch(ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null,"Class Error. Contact System Admin");
        } catch(SQLException e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Unknown Error. Contact System Admin");
        } finally {
            try {
                  if(con!=null) con.close();
                  
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin");
            }
            try {
                  if(stmt!=null) stmt.close();
                  
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin");
            }
            
        }
    }//GEN-LAST:event_b_updateActionPerformed

    private void b_changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_changePasswordActionPerformed
        new changePassword(user_id).setVisible(true);
    }//GEN-LAST:event_b_changePasswordActionPerformed

    private void b_changeUNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_changeUNameActionPerformed
        new changeUsername(user_id).setVisible(true);
    }//GEN-LAST:event_b_changeUNameActionPerformed

    /**
     * @param args the command line arguments
     */
//     public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_changePassword;
    private javax.swing.JButton b_changeUName;
    private javax.swing.JButton b_update;
    private javax.swing.ButtonGroup genderset;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_District;
    private javax.swing.JLabel l_email;
    private javax.swing.JLabel l_fullname;
    private javax.swing.JLabel l_gender;
    private javax.swing.JLabel l_localbody;
    private javax.swing.JLabel l_localbody1;
    private javax.swing.JLabel l_phone1;
    private javax.swing.JLabel l_rname;
    private javax.swing.JLabel l_wardnumber;
    private javax.swing.JPanel p_regblu;
    private javax.swing.JPanel p_regorg;
    private javax.swing.JLabel t_address;
    private javax.swing.JLabel t_blood;
    private javax.swing.JTextArea ta_address;
    private javax.swing.JTextField tf_blood_group;
    private javax.swing.JTextField tf_body;
    private javax.swing.JTextField tf_bodytype;
    private javax.swing.JTextField tf_dateofbirth;
    private javax.swing.JTextField tf_district;
    private javax.swing.JLabel tf_dob;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_fullname;
    private javax.swing.JTextField tf_gender;
    private javax.swing.JTextField tf_phonenumber;
    private javax.swing.JTextField tf_wardnumber;
    // End of variables declaration//GEN-END:variables
    Connection con;
    PreparedStatement stmt;
    int user_id;
}
