/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asdtemp;

import java.awt.Color;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Base64;

/**
 *
 * @author Sourav Menon
 */
public class register_form extends javax.swing.JFrame {

    /**
     * Creates new form register_form
     */
    public register_form() {
        initComponents();
        this.setLocationRelativeTo(null);
        fetch();
    }
    private void fetch() {
        try {
            
            con = new Connector().getCon();
            stmt=con.prepareStatement("SELECT dist_name FROM asdproject.districts;");
            ResultSet rs=stmt.executeQuery();
            int size =0;
            if (rs != null) 
            {
              rs.last();    // moves cursor to the last row
              size = rs.getRow(); // get row id 
            }
            rs.first();
            distnames=new String[size];
            int i=0;
            do{
            distnames[i++]=rs.getString(1);
            }while(rs.next());
             cb_Rdistrict.setModel(new javax.swing.DefaultComboBoxModel<>(distnames));
             
            stmt=con.prepareStatement("SELECT type FROM asdproject.localbodytype;");
             rs=stmt.executeQuery();
             size =0;
            if (rs != null) 
            {
              rs.last();    // moves cursor to the last row
              size = rs.getRow(); // get row id 
            }
            rs.first();
            lb_types=new String[size];
             i=0;
            do{
            lb_types[i++]=rs.getString(1);
            }while(rs.next());
             cb_Rlocalbodytype.setModel(new javax.swing.DefaultComboBoxModel<>(lb_types));
              }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Class Missing. Contact System Admin.");
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null,"Unknown Error. Contact System Admin.");
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        genderset = new javax.swing.ButtonGroup();
        p_regorg = new javax.swing.JPanel();
        l_rname = new javax.swing.JLabel();
        p_regblu = new javax.swing.JPanel();
        l_name = new javax.swing.JLabel();
        tf_phone = new javax.swing.JTextField();
        l_pass = new javax.swing.JLabel();
        pf_password = new javax.swing.JPasswordField();
        l_cpass = new javax.swing.JLabel();
        pf_confirmpassword = new javax.swing.JPasswordField();
        l_fullname = new javax.swing.JLabel();
        tf_fullname = new javax.swing.JTextField();
        tf_dob = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        l_gender = new javax.swing.JLabel();
        b_register = new javax.swing.JButton();
        b_cancel = new javax.swing.JButton();
        l_registerlogin = new javax.swing.JLabel();
        dc_dob = new com.toedter.calendar.JDateChooser();
        l_phone1 = new javax.swing.JLabel();
        l_District = new javax.swing.JLabel();
        l_localbody = new javax.swing.JLabel();
        l_wardnumber = new javax.swing.JLabel();
        l_email = new javax.swing.JLabel();
        t_blood = new javax.swing.JLabel();
        t_address = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_address = new javax.swing.JTextArea();
        cb_Rdistrict = new javax.swing.JComboBox<>();
        cb_Rlocalbodytype = new javax.swing.JComboBox<>();
        cb_bloodgrp = new javax.swing.JComboBox<>();
        cb_Rlocalbody = new javax.swing.JComboBox<>();
        l_localbody1 = new javax.swing.JLabel();
        cb_Rwardnumber = new javax.swing.JComboBox<>();
        rb_male = new javax.swing.JRadioButton();
        rb_female = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        p_regorg.setBackground(new java.awt.Color(250, 216, 89));

        l_rname.setBackground(new java.awt.Color(250, 216, 89));
        l_rname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_rname.setText("REGISTER");

        javax.swing.GroupLayout p_regorgLayout = new javax.swing.GroupLayout(p_regorg);
        p_regorg.setLayout(p_regorgLayout);
        p_regorgLayout.setHorizontalGroup(
            p_regorgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_regorgLayout.createSequentialGroup()
                .addGap(437, 437, 437)
                .addComponent(l_rname, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(499, Short.MAX_VALUE))
        );
        p_regorgLayout.setVerticalGroup(
            p_regorgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_regorgLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(l_rname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        p_regblu.setBackground(new java.awt.Color(51, 110, 123));
        p_regblu.setPreferredSize(new java.awt.Dimension(417, 500));

        l_name.setBackground(new java.awt.Color(149, 165, 166));
        l_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_name.setForeground(new java.awt.Color(243, 241, 239));
        l_name.setText("Username :");

        tf_phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_phoneKeyReleased(evt);
            }
        });

        l_pass.setBackground(new java.awt.Color(149, 165, 166));
        l_pass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_pass.setForeground(new java.awt.Color(243, 241, 239));
        l_pass.setText("Password :");

        pf_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_passwordActionPerformed(evt);
            }
        });

        l_cpass.setBackground(new java.awt.Color(149, 165, 166));
        l_cpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_cpass.setForeground(new java.awt.Color(243, 241, 239));
        l_cpass.setText("Confirm Password :");

        pf_confirmpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_confirmpasswordActionPerformed(evt);
            }
        });

        l_fullname.setBackground(new java.awt.Color(149, 165, 166));
        l_fullname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_fullname.setForeground(new java.awt.Color(243, 241, 239));
        l_fullname.setText("Full Name :");

        tf_fullname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_fullname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tf_dob.setBackground(new java.awt.Color(149, 165, 166));
        tf_dob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tf_dob.setForeground(new java.awt.Color(243, 241, 239));
        tf_dob.setText("Date of Birth :");

        tf_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usernameActionPerformed(evt);
            }
        });
        tf_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_usernameKeyReleased(evt);
            }
        });

        l_gender.setBackground(new java.awt.Color(149, 165, 166));
        l_gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_gender.setForeground(new java.awt.Color(243, 241, 239));
        l_gender.setText("Gender");

        b_register.setBackground(new java.awt.Color(25, 181, 254));
        b_register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_register.setText("Register");
        b_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_registerActionPerformed(evt);
            }
        });

        b_cancel.setBackground(new java.awt.Color(207, 0, 15));
        b_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_cancel.setText("Cancel");
        b_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        l_registerlogin.setBackground(new java.awt.Color(0, 230, 64));
        l_registerlogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_registerlogin.setForeground(new java.awt.Color(243, 241, 239));
        l_registerlogin.setText("Click here to login ");
        l_registerlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l_registerlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_registerloginMouseClicked(evt);
            }
        });

        dc_dob.setBackground(new java.awt.Color(149, 165, 166));

        l_phone1.setBackground(new java.awt.Color(149, 165, 166));
        l_phone1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_phone1.setForeground(new java.awt.Color(243, 241, 239));
        l_phone1.setText("Phone Number :");

        l_District.setBackground(new java.awt.Color(149, 165, 166));
        l_District.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_District.setForeground(new java.awt.Color(243, 241, 239));
        l_District.setText("District :");

        l_localbody.setBackground(new java.awt.Color(149, 165, 166));
        l_localbody.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_localbody.setForeground(new java.awt.Color(243, 241, 239));
        l_localbody.setText("Select Body type");

        l_wardnumber.setBackground(new java.awt.Color(149, 165, 166));
        l_wardnumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_wardnumber.setForeground(new java.awt.Color(243, 241, 239));
        l_wardnumber.setText("Ward Number :");

        l_email.setBackground(new java.awt.Color(149, 165, 166));
        l_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_email.setForeground(new java.awt.Color(243, 241, 239));
        l_email.setText("Email id :");

        t_blood.setBackground(new java.awt.Color(149, 165, 166));
        t_blood.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t_blood.setForeground(new java.awt.Color(243, 241, 239));
        t_blood.setText("Blood Group :");

        t_address.setBackground(new java.awt.Color(149, 165, 166));
        t_address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t_address.setForeground(new java.awt.Color(243, 241, 239));
        t_address.setText("Address :");

        tf_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });
        tf_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_emailKeyReleased(evt);
            }
        });

        ta_address.setColumns(20);
        ta_address.setRows(5);
        jScrollPane1.setViewportView(ta_address);

        cb_Rdistrict.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_Rdistrict.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "District", "Thiruvanathapuram", "Kollam", "Pathanamthitta", "Alappuzha ", "Kottayam", "Idukki", "Ernakulam", "Thrissur", "Palakkad", "Malappuram'", "Kozhikode", "Wayanad", "Kannur", "Kasargod" }));
        cb_Rdistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_RdistrictActionPerformed(evt);
            }
        });

        cb_Rlocalbodytype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_Rlocalbodytype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cb_Rlocalbodytype.setToolTipText("");
        cb_Rlocalbodytype.setEnabled(false);
        cb_Rlocalbodytype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_RlocalbodytypeActionPerformed(evt);
            }
        });

        cb_bloodgrp.setEditable(true);
        cb_bloodgrp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_bloodgrp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-", "OTHER" }));

        cb_Rlocalbody.setEditable(true);
        cb_Rlocalbody.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_Rlocalbody.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cb_Rlocalbody.setToolTipText("");
        cb_Rlocalbody.setEnabled(false);
        cb_Rlocalbody.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_RlocalbodyActionPerformed(evt);
            }
        });

        l_localbody1.setBackground(new java.awt.Color(149, 165, 166));
        l_localbody1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_localbody1.setForeground(new java.awt.Color(243, 241, 239));
        l_localbody1.setText("Select Body ");

        cb_Rwardnumber.setEditable(true);
        cb_Rwardnumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_Rwardnumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cb_Rwardnumber.setEnabled(false);

        rb_male.setBackground(new java.awt.Color(51, 110, 123));
        genderset.add(rb_male);
        rb_male.setForeground(new java.awt.Color(255, 255, 255));
        rb_male.setText("Male");

        rb_female.setBackground(new java.awt.Color(51, 110, 123));
        genderset.add(rb_female);
        rb_female.setForeground(new java.awt.Color(255, 255, 255));
        rb_female.setText("Female");

        javax.swing.GroupLayout p_regbluLayout = new javax.swing.GroupLayout(p_regblu);
        p_regblu.setLayout(p_regbluLayout);
        p_regbluLayout.setHorizontalGroup(
            p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_regbluLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(p_regbluLayout.createSequentialGroup()
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_blood, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_phone)
                            .addComponent(cb_bloodgrp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_regbluLayout.createSequentialGroup()
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(p_regbluLayout.createSequentialGroup()
                                            .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(p_regbluLayout.createSequentialGroup()
                                                    .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(l_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(l_email, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(53, 53, 53))
                                                .addGroup(p_regbluLayout.createSequentialGroup()
                                                    .addComponent(tf_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGap(27, 27, 27)))
                                            .addGap(22, 22, 22))
                                        .addGroup(p_regbluLayout.createSequentialGroup()
                                            .addComponent(l_gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(31, 31, 31)))
                                    .addGroup(p_regbluLayout.createSequentialGroup()
                                        .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(75, 75, 75)))
                                .addGroup(p_regbluLayout.createSequentialGroup()
                                    .addComponent(l_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(92, 92, 92)))
                            .addGroup(p_regbluLayout.createSequentialGroup()
                                .addComponent(l_cpass)
                                .addGap(55, 55, 55)))
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pf_confirmpassword)
                            .addComponent(pf_password)
                            .addComponent(tf_username)
                            .addComponent(dc_dob, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(tf_email)
                            .addComponent(tf_fullname)
                            .addGroup(p_regbluLayout.createSequentialGroup()
                                .addComponent(rb_male)
                                .addGap(18, 18, 18)
                                .addComponent(rb_female, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(22, 22, 22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_regbluLayout.createSequentialGroup()
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(l_localbody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(l_wardnumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_District, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_Rdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_Rlocalbodytype, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_Rlocalbody, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_Rwardnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(l_localbody1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(p_regbluLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(b_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(b_register, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(p_regbluLayout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(l_registerlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_regbluLayout.setVerticalGroup(
            p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_regbluLayout.createSequentialGroup()
                .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_regbluLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p_regbluLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_District, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_Rdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_localbody, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_Rlocalbodytype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_localbody1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_Rlocalbody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_regbluLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pf_password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_cpass, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pf_confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dc_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_gender)
                            .addComponent(rb_male)
                            .addComponent(rb_female)))
                    .addGroup(p_regbluLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l_wardnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_Rwardnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_address, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_blood, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_bloodgrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(p_regbluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_register, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(l_registerlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(288, 288, 288))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_regorg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_regblu, javax.swing.GroupLayout.DEFAULT_SIZE, 1009, Short.MAX_VALUE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_regorg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_regblu, javax.swing.GroupLayout.PREFERRED_SIZE, 653, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pf_confirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_confirmpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_confirmpasswordActionPerformed

    private void l_registerloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_registerloginMouseClicked
        this.dispose();      
        new Login().setVisible(true);
    }//GEN-LAST:event_l_registerloginMouseClicked

    private void b_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_registerActionPerformed
        // TODO add your handling code here:
         try
        {   con = new Connector().getCon();
            lb_name=cb_Rlocalbody.getSelectedItem().toString();
            stmt=con.prepareStatement("SELECT p_id FROM asdproject.panchayaths WHERE p_name=?;");
            stmt.setString(1,lb_name);
            ResultSet rs=stmt.executeQuery();
            if(rs.next())
                lb_name_id=rs.getInt(1);
            ward_no=Integer.valueOf(cb_Rwardnumber.getSelectedItem().toString());
            DateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");  
            String dob = dateFormat.format(dc_dob.getDate()); 
            String fullname=tf_fullname.getText();
            String phonenumber=tf_phone.getText();
            String email=tf_email.getText();
            String username=tf_username.getText();
            String password=new String(pf_password.getPassword());
            String reenterpassword=new String(pf_confirmpassword.getPassword());
            String address=ta_address.getText();
            String bloodgp=cb_bloodgrp.getSelectedItem().toString();
            String gender="";
            if(rb_male.isSelected())
                gender=rb_male.getText();
            else if(rb_female.isSelected())
                gender=rb_female.getText();
            else
                   JOptionPane.showMessageDialog(null,"Select a gender","Invalid Gender",JOptionPane.ERROR_MESSAGE);    
            con = new Connector().getCon();
            stmt=con.prepareStatement("SELECT * FROM asdproject.citizen_list WHERE c_user_name=?;");
            stmt.setString(1,username);
             rs=stmt.executeQuery();
            if(!rs.next()) {
                if(phonenumber.length()!=10)
                    JOptionPane.showMessageDialog(null,"Provide a valid 10 digit mobile number","Invalid Phone Number",JOptionPane.ERROR_MESSAGE);
                else {
                    if (fullname.equals("")||email.equals("")||password.equals("")||phonenumber.equals("")||reenterpassword.equals("")||address.equals("") )
                        JOptionPane.showMessageDialog(null,"All fields are required","Insufficient data",JOptionPane.ERROR_MESSAGE);
                    else {
                            if (password.equals(reenterpassword)) {
                                stmt=con.prepareStatement("INSERT INTO asdproject.`citizen_list` (`c_fullname`, `c_email`, `c_user_name`, `c_pass`, `c_phno`, `c_gender`, `c_blood_grp`, `c_dob`, `c_district_id`, `c_local_body_type_id`, `c_local_body_name_id`, `c_ward_num`, `c_address`) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);");
                                stmt.setString(1,fullname);
                                stmt.setString(2,email);
                                stmt.setString(3,username);
                                stmt.setString(4,Base64.getEncoder().encodeToString(password.getBytes()));
                                stmt.setString(5,phonenumber);
                                stmt.setString(6,gender);
                                stmt.setString(7,bloodgp);
                                stmt.setString(8,dob);
                                stmt.setInt(9,dist_id);
                                stmt.setInt(10,lb_type_id);
                                stmt.setInt(11,lb_name_id);
                                stmt.setInt(12,ward_no);
                                stmt.setString(13,address);
                                int flag = stmt.executeUpdate();
                                if(flag==1)
                                {
                                    JOptionPane.showMessageDialog(null,"Registration Succesfull. Please Login to continue");
                                    tf_fullname.setText("");
                                    tf_phone.setText("");
                                    tf_username.setText("");
                                    tf_email.setText("");
                                    pf_password.setText("");
                                    pf_confirmpassword.setText("");
                                    ta_address.setText("");
                                    cb_Rlocalbodytype.setEnabled(false);
                                    cb_Rwardnumber.setEnabled(false);
                                    cb_Rlocalbody.setEnabled(false);

                                }

                            } 
                            else {
                                JOptionPane.showMessageDialog(null,"Passwords do not match!","Invalid Input",JOptionPane.ERROR_MESSAGE);
                            }
                        
                    }
                }
            }
            else {
                JOptionPane.showMessageDialog(null,"User with same username already registered");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin.");
            //ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Class Missing. Contact System Admin.");
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null,"Unknown Error. Contact System Admin.");
            //ex.printStackTrace();
        } 
    }//GEN-LAST:event_b_registerActionPerformed

    private void tf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usernameActionPerformed

    }//GEN-LAST:event_tf_usernameActionPerformed

    private void tf_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_usernameKeyReleased
        
        
    }//GEN-LAST:event_tf_usernameKeyReleased

    private void tf_phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_phoneKeyReleased
        String mobileno= tf_phone.getText();
        if(mobileno.matches("^[0-9]*$") && mobileno.length()==10)
        {
            tf_phone.setBackground(Color.green);
        }
        else
        {
            tf_phone.setBackground(Color.red);
        }
    }//GEN-LAST:event_tf_phoneKeyReleased

    private void pf_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_passwordActionPerformed

    private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_emailActionPerformed

    private void tf_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_emailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_emailKeyReleased

    private void cb_RdistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_RdistrictActionPerformed
        // TODO add your handling code here:
        cb_Rlocalbodytype.setEnabled(true);
         
    }//GEN-LAST:event_cb_RdistrictActionPerformed

    private void cb_RlocalbodytypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_RlocalbodytypeActionPerformed
        // TODO add your handling code here:
        try {
            con = new Connector().getCon();
            dist=cb_Rdistrict.getSelectedItem().toString();
            lb_type=cb_Rlocalbodytype.getSelectedItem().toString();
            if(lb_type.equals("GRAMA PANCHAYATH"))
            {
            lb_type_id=3;
            stmt=con.prepareStatement("SELECT dist_id FROM asdproject.districts where dist_name=? ;");
            stmt.setString(1,dist);        
            ResultSet rs=stmt.executeQuery();
            rs.first();
            dist_id=rs.getInt(1);
            stmt=con.prepareStatement("SELECT p_name,p_id FROM asdproject.panchayaths where d_id=? ;");
            stmt.setString(1,rs.getString(1));
            rs=stmt.executeQuery();
            int size =0;
            if (rs != null) 
            {
              rs.last();    // moves cursor to the last row
              size = rs.getRow(); // get row id 
            }
            rs.first();
            local_body_list=new String[size];
            int i=0;
            do{
            local_body_list[i++]=rs.getString(1);
            }while(rs.next());
             cb_Rlocalbody.setModel(new javax.swing.DefaultComboBoxModel<>(local_body_list));
            }
            cb_Rlocalbody.setEnabled(true);
        }
        catch (SQLException ex) {
            //ex.printStackTrace();
            JOptionPane.showMessageDialog(null,"SQL Error. Contact System Admin.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Class Missing. Contact System Admin.");
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null,"Unknown Error. Contact System Admin.");
        } 
    }//GEN-LAST:event_cb_RlocalbodytypeActionPerformed

    private void cb_RlocalbodyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_RlocalbodyActionPerformed
        // TODO add your handling code here:
        cb_Rwardnumber.setEnabled(true);
    }//GEN-LAST:event_cb_RlocalbodyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cancel;
    private javax.swing.JButton b_register;
    private javax.swing.JComboBox<String> cb_Rdistrict;
    private javax.swing.JComboBox<String> cb_Rlocalbody;
    private javax.swing.JComboBox<String> cb_Rlocalbodytype;
    private javax.swing.JComboBox<String> cb_Rwardnumber;
    private javax.swing.JComboBox<String> cb_bloodgrp;
    private com.toedter.calendar.JDateChooser dc_dob;
    private javax.swing.ButtonGroup genderset;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_District;
    private javax.swing.JLabel l_cpass;
    private javax.swing.JLabel l_email;
    private javax.swing.JLabel l_fullname;
    private javax.swing.JLabel l_gender;
    private javax.swing.JLabel l_localbody;
    private javax.swing.JLabel l_localbody1;
    private javax.swing.JLabel l_name;
    private javax.swing.JLabel l_pass;
    private javax.swing.JLabel l_phone1;
    private javax.swing.JLabel l_registerlogin;
    private javax.swing.JLabel l_rname;
    private javax.swing.JLabel l_wardnumber;
    private javax.swing.JPanel p_regblu;
    private javax.swing.JPanel p_regorg;
    private javax.swing.JPasswordField pf_confirmpassword;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JRadioButton rb_female;
    private javax.swing.JRadioButton rb_male;
    private javax.swing.JLabel t_address;
    private javax.swing.JLabel t_blood;
    private javax.swing.JTextArea ta_address;
    private javax.swing.JLabel tf_dob;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_fullname;
    private javax.swing.JTextField tf_phone;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
    Connection con;
    PreparedStatement stmt;
    String distnames[];
    String lb_types[];
    String local_body_list[];
    String dist;
    String lb_type;
    String lb_name;
    int dist_id;
    int lb_type_id;
    int lb_name_id;
    int ward_no;

    
}
