/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asdtemp;

import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import javax.swing.table.*;
/**
 *
 * @author ajayj
 */
public class Removecfltc extends javax.swing.JFrame {

    /**
     * Creates new form Sample
     */
    public Removecfltc() {
        initComponents();
        this.setLocationRelativeTo(null);
        fillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        l_district = new javax.swing.JLabel();
        cb_selectdistrict = new javax.swing.JComboBox<>();
        l_district1 = new javax.swing.JLabel();
        tf_selectcfltc = new javax.swing.JTextField();
        l_title1 = new javax.swing.JLabel();
        b_proceed = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_removecfltc = new javax.swing.JTable();
        b_removecftlc = new javax.swing.JButton();
        l_title2 = new javax.swing.JLabel();
        l_icon = new javax.swing.JLabel();
        l_icon1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(997, 628));

        jPanel2.setBackground(new java.awt.Color(46, 49, 49));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Remove CFLTC ");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/images.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        l_district.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_district.setText("Selected CFLTC     :  ");

        cb_selectdistrict.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "District", "Thiruvanathapuram", "Kollam", "Pathanamthitta", "Alappuzha ", "Kottayam", "Idukki", "Ernakulam", "Thrissur", "Palakkad", "Malappuram'", "Kozhikode", "Wayanad", "Kannur", "Kasargod" }));

        l_district1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_district1.setText("Select District     :");

        tf_selectcfltc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_selectcfltcActionPerformed(evt);
            }
        });

        l_title1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_title1.setText("CFLTC in ");

        b_proceed.setBackground(new java.awt.Color(40, 167, 69));
        b_proceed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b_proceed.setText("Proceed ");
        b_proceed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_proceedActionPerformed(evt);
            }
        });

        t_removecfltc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_removecfltc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_removecfltcMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_removecfltc);

        b_removecftlc.setBackground(new java.awt.Color(255, 193, 7));
        b_removecftlc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b_removecftlc.setText("Remove CFLTC");
        b_removecftlc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_removecftlc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_removecftlcActionPerformed(evt);
            }
        });

        l_title2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_title2.setText("CFLTC");

        l_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/bullet.png"))); // NOI18N
        l_icon.setToolTipText("");

        l_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/bullet.png"))); // NOI18N
        l_icon1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(l_district1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(cb_selectdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(l_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(l_title2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(b_proceed, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(l_icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(l_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(l_district, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(tf_selectcfltc, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(b_removecftlc, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(371, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_title2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_district1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_selectdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(b_proceed, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(l_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_district, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_selectcfltc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(b_removecftlc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_selectcfltcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_selectcfltcActionPerformed

    }//GEN-LAST:event_tf_selectcfltcActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void b_proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_proceedActionPerformed
        int district = cb_selectdistrict.getSelectedIndex()+1;
        l_title1.setText("CFLTC in "+cb_selectdistrict.getSelectedItem().toString());
        try{
            Connection con = new Connector().getCon();
            PreparedStatement ps = con.prepareStatement("SELECT cfltc_id, cfltc_name, cfltc_address FROM asdproject.cfltc WHERE cfltc_district_id=?");
            ps.setInt(1, district);
            
            ResultSet rs = ps.executeQuery();
            t_removecfltc.setModel(DbUtils.resultSetToTableModel(rs));
            if(!rs.first())
            JOptionPane.showMessageDialog(null,"No CFLTC Registered in "+district,"Error",JOptionPane.ERROR_MESSAGE);
        } catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error. Contact System Admin.");
    }
    }//GEN-LAST:event_b_proceedActionPerformed

    private void b_removecftlcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_removecftlcActionPerformed
        DefaultTableModel model = (DefaultTableModel) t_removecfltc.getModel();
        
        int RowIndex = t_removecfltc.getSelectedRow();
        String id = t_removecfltc.getModel().getValueAt(RowIndex, 0).toString();
        
         try{
            Connection con = new Connector().getCon();
            PreparedStatement ps = con.prepareStatement("DELETE FROM asdproject.cfltc WHERE cfltc_id=?");
            ps.setString(1, id);
            
            int rs = ps.executeUpdate();
            model.removeRow(RowIndex);
            tf_selectcfltc.setText("");
            if(rs!=0)
            {
                 JOptionPane.showMessageDialog(null,"CFLTC Removed Sucessfully");
            }
            else
               JOptionPane.showMessageDialog(null,"CFLTC Not Removed","Error",JOptionPane.ERROR_MESSAGE);
            
        } catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error. Contact System Admin.");
    }
        
    }//GEN-LAST:event_b_removecftlcActionPerformed

    private void t_removecfltcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_removecfltcMouseClicked
        int row = t_removecfltc.getSelectedRow();
        TableModel model = t_removecfltc.getModel();
        
        tf_selectcfltc.setText(model.getValueAt(row,1).toString());
    }//GEN-LAST:event_t_removecfltcMouseClicked

    private void cb_selectdistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_selectdistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_selectdistrictActionPerformed
    private void fillCombo(){
        try{
                 
                 Connection con = new Connector().getCon();
                 PreparedStatement ps=con.prepareStatement("SELECT dist_name FROM asdproject.districts;");
                 ResultSet rs = ps.executeQuery();
                 int size = 0;
                 if (rs != null) 
                {
                    rs.last();    // moves cursor to the last row
                    size = rs.getRow(); // get row id 
                }
                rs.first();
                String[] distnames = new String[size];
                int i=0;
                do{
                    distnames[i++]=rs.getString(1);
                }while(rs.next());
                cb_selectdistrict.setModel(new javax.swing.DefaultComboBoxModel<>(distnames));
  
   
        }catch(Exception e){
           // System.out.println("Error in fillCombo");  
         JOptionPane.showMessageDialog(null,"Error. Contact System Admin.");}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Removecfltc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Removecfltc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Removecfltc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Removecfltc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Removecfltc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_proceed;
    private javax.swing.JButton b_removecftlc;
    private javax.swing.JComboBox<String> cb_selectdistrict;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_district;
    private javax.swing.JLabel l_district1;
    private javax.swing.JLabel l_icon;
    private javax.swing.JLabel l_icon1;
    private javax.swing.JLabel l_title1;
    private javax.swing.JLabel l_title2;
    private javax.swing.JTable t_removecfltc;
    private javax.swing.JTextField tf_selectcfltc;
    // End of variables declaration//GEN-END:variables
}
