/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asdtemp;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ajayj
 */
public class RemoveVolunteer extends javax.swing.JFrame {

    /**
     * Creates new form FAQ
     */
    public RemoveVolunteer() {
        initComponents();
        this.setLocationRelativeTo(null);
        fetch();
    }
     private void fetch() {
        try {
            
            Connection con = new Connector().getCon();
            PreparedStatement stmt=con.prepareStatement("SELECT dist_name FROM asdproject.districts;");
            ResultSet rs=stmt.executeQuery();
            int size =0;
            if (rs != null) 
            {
              rs.last();    // moves cursor to the last row
              size = rs.getRow(); // get row id 
            }
            rs.first();
            String [] distnames=new String[size];
            int i=0;
            do{
            distnames[i++]=rs.getString(1);
            }while(rs.next());
             cb_Rdistrict.setModel(new javax.swing.DefaultComboBoxModel<>(distnames));
             
            stmt=con.prepareStatement("SELECT type FROM asdproject.localbodytype;");
             rs=stmt.executeQuery();
             size =0;
            if (rs != null) 
            {
              rs.last();    // moves cursor to the last row
              size = rs.getRow(); // get row id 
            }
            rs.first();
            String lb_types[]=new String[size];
             i=0;
            do{
            lb_types[i++]=rs.getString(1);
            }while(rs.next());
             cb_Rlocalbodytype.setModel(new javax.swing.DefaultComboBoxModel<>(lb_types));
              }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Class Missing. Contact System Admin.");
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null,"Unknown Error. Contact System Admin.");
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_toppanel = new javax.swing.JPanel();
        l_title = new javax.swing.JLabel();
        img_back = new javax.swing.JLabel();
        p_main = new javax.swing.JPanel();
        l_regHealthWorkers = new javax.swing.JLabel();
        sp_healthWorkers = new javax.swing.JScrollPane();
        t_volunteers = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        l_wokerID = new javax.swing.JLabel();
        tf_volunteerid = new javax.swing.JTextField();
        b_remove = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cb_Rdistrict = new javax.swing.JComboBox<>();
        cb_Rlocalbodytype = new javax.swing.JComboBox<>();
        l_localbody = new javax.swing.JLabel();
        l_District = new javax.swing.JLabel();
        l_localbody1 = new javax.swing.JLabel();
        cb_Rlocalbody = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tf_volunteername = new javax.swing.JTextField();
        l_wokerID1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 750));
        setResizable(false);
        getContentPane().setLayout(null);

        p_toppanel.setBackground(new java.awt.Color(46, 49, 49));
        p_toppanel.setLayout(null);

        l_title.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        l_title.setForeground(new java.awt.Color(255, 255, 255));
        l_title.setText("Remove Volunteer");
        p_toppanel.add(l_title);
        l_title.setBounds(70, 10, 340, 41);

        img_back.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        img_back.setForeground(new java.awt.Color(255, 255, 255));
        img_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/back2.png"))); // NOI18N
        img_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        img_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_backMouseClicked(evt);
            }
        });
        p_toppanel.add(img_back);
        img_back.setBounds(20, 10, 40, 40);

        getContentPane().add(p_toppanel);
        p_toppanel.setBounds(0, 0, 960, 60);

        p_main.setBackground(new java.awt.Color(232, 236, 241));
        p_main.setMinimumSize(new java.awt.Dimension(900, 740));

        l_regHealthWorkers.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        l_regHealthWorkers.setText("Registered Volunteers");

        t_volunteers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_volunteers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_volunteersMouseClicked(evt);
            }
        });
        sp_healthWorkers.setViewportView(t_volunteers);

        l_wokerID.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_wokerID.setText("Selected Volunteer ID");

        tf_volunteerid.setEditable(false);

        b_remove.setBackground(new java.awt.Color(23, 162, 184));
        b_remove.setText("Remove");
        b_remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_removeActionPerformed(evt);
            }
        });

        cb_Rdistrict.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_Rdistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_RdistrictActionPerformed(evt);
            }
        });

        cb_Rlocalbodytype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_Rlocalbodytype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cb_Rlocalbodytype.setToolTipText("");
        cb_Rlocalbodytype.setEnabled(false);
        cb_Rlocalbodytype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_RlocalbodytypeActionPerformed(evt);
            }
        });

        l_localbody.setBackground(new java.awt.Color(149, 165, 166));
        l_localbody.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_localbody.setText("Select Body type");

        l_District.setBackground(new java.awt.Color(149, 165, 166));
        l_District.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_District.setText("District :");

        l_localbody1.setBackground(new java.awt.Color(149, 165, 166));
        l_localbody1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_localbody1.setText("Select Body ");

        cb_Rlocalbody.setEditable(true);
        cb_Rlocalbody.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_Rlocalbody.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cb_Rlocalbody.setToolTipText("");
        cb_Rlocalbody.setEnabled(false);
        cb_Rlocalbody.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_RlocalbodyActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Select the row of Volunteer to be removed");

        tf_volunteername.setEditable(false);

        l_wokerID1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_wokerID1.setText("Selected Volunteer Name");

        javax.swing.GroupLayout p_mainLayout = new javax.swing.GroupLayout(p_main);
        p_main.setLayout(p_mainLayout);
        p_mainLayout.setHorizontalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_mainLayout.createSequentialGroup()
                .addGap(0, 56, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(p_mainLayout.createSequentialGroup()
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_mainLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(p_mainLayout.createSequentialGroup()
                                .addComponent(l_localbody1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_Rlocalbody, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_mainLayout.createSequentialGroup()
                                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(l_localbody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(l_District, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_Rdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_Rlocalbodytype, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(p_mainLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sp_healthWorkers, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(p_mainLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(l_regHealthWorkers))))
                    .addGroup(p_mainLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel2))
                    .addGroup(p_mainLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(p_mainLayout.createSequentialGroup()
                                .addComponent(l_wokerID1)
                                .addGap(166, 166, 166)
                                .addComponent(tf_volunteername, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_mainLayout.createSequentialGroup()
                                .addComponent(l_wokerID)
                                .addGap(166, 166, 166)
                                .addComponent(tf_volunteerid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(p_mainLayout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(b_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_mainLayout.setVerticalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_District, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Rdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_localbody, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Rlocalbodytype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_localbody1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Rlocalbody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_regHealthWorkers)
                .addGap(18, 18, 18)
                .addComponent(sp_healthWorkers, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_wokerID)
                    .addComponent(tf_volunteerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_wokerID1)
                    .addComponent(tf_volunteername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(b_remove)
                .addGap(158, 158, 158))
        );

        getContentPane().add(p_main);
        p_main.setBounds(0, 60, 960, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void img_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_backMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_img_backMouseClicked

    private void cb_RlocalbodyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_RlocalbodyActionPerformed
        // TODO add your handling code here:
        String body = cb_Rlocalbody.getSelectedItem().toString();
        
        try{
            Connection con = new Connector().getCon();
            PreparedStatement ps = con.prepareStatement("SELECT vl.v_id, cl.c_fullname, cl.c_phno, vl.languages_known, vl.work_type FROM asdproject.volunteer_list vl, asdproject.citizen_list cl, asdproject.districts d, asdproject.panchayaths p where vl.citizen_id=cl.c_id and p.p_id=cl.c_local_body_name_id and d.dist_name=? AND p.p_name=?;");
            ps.setString(1, cb_Rdistrict.getSelectedItem().toString());
            ps.setString(2, cb_Rlocalbody.getSelectedItem().toString());
            ResultSet rs = ps.executeQuery();
            t_volunteers.setModel(DbUtils.resultSetToTableModel(rs));
            if(!rs.first())
            JOptionPane.showMessageDialog(null,"No Volunteers Registered in "+cb_Rlocalbody.getSelectedItem().toString());
        } catch(Exception e){
            //e.printStackTrace();
        JOptionPane.showMessageDialog(null,"Error. Contact System Admin.");
    }
        
        
    }//GEN-LAST:event_cb_RlocalbodyActionPerformed

    private void cb_RlocalbodytypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_RlocalbodytypeActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = new Connector().getCon();
            dist=cb_Rdistrict.getSelectedItem().toString();
            lb_type=cb_Rlocalbodytype.getSelectedItem().toString();
            if(lb_type.equals("GRAMA PANCHAYATH"))
            {
                //int lb_type_id=3;
                PreparedStatement stmt=con.prepareStatement("SELECT dist_id FROM asdproject.districts where dist_name=? ;");
                stmt.setString(1,dist);
                ResultSet rs=stmt.executeQuery();
                rs.first();
                stmt=con.prepareStatement("SELECT p_name,p_id FROM asdproject.panchayaths where d_id=? ;");
                stmt.setString(1,rs.getString(1));
                rs=stmt.executeQuery();
                int size =0;
                if (rs != null)
                {
                    rs.last();    // moves cursor to the last row
                    size = rs.getRow(); // get row id
                }
                rs.first();
                String local_body_list[]=new String[size];
                int i=0;
                do{
                    local_body_list[i++]=rs.getString(1);
                }while(rs.next());
                cb_Rlocalbody.setModel(new javax.swing.DefaultComboBoxModel<>(local_body_list));
            }
            cb_Rlocalbody.setEnabled(true);
        }
        catch (SQLException ex) {
            //ex.printStackTrace();
            JOptionPane.showMessageDialog(null,"SQL Error. Contact System Admin.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Class Missing. Contact System Admin.");
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null,"Unknown Error. Contact System Admin.");
        } 
        
    }//GEN-LAST:event_cb_RlocalbodytypeActionPerformed

    private void cb_RdistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_RdistrictActionPerformed
        // TODO add your handling code here:
        cb_Rlocalbodytype.setEnabled(true);
    }//GEN-LAST:event_cb_RdistrictActionPerformed

    private void t_volunteersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_volunteersMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) t_volunteers.getModel();
        
        int RowIndex = t_volunteers.getSelectedRow();
        tf_volunteerid.setText(t_volunteers.getModel().getValueAt(RowIndex, 0).toString());
        tf_volunteername.setText(t_volunteers.getModel().getValueAt(RowIndex, 1).toString());
         
    }//GEN-LAST:event_t_volunteersMouseClicked

    private void b_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_removeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) t_volunteers.getModel();
        
        int RowIndex = t_volunteers.getSelectedRow();
        String id = t_volunteers.getModel().getValueAt(RowIndex, 0).toString();
        try{
            Connection con = new Connector().getCon();
            PreparedStatement ps = con.prepareStatement("DELETE FROM asdproject.volunteer_list WHERE v_id=?");
            ps.setString(1, id);
            
            int rs = ps.executeUpdate();
            model.removeRow(RowIndex);
            if(rs!=0)
            {
                 JOptionPane.showMessageDialog(null,"Volunteer Removed Sucessfully");
                 tf_volunteerid.setText("");
                 tf_volunteername.setText("");
            }
            else
               JOptionPane.showMessageDialog(null,"Volunteer Not Removed","Error",JOptionPane.ERROR_MESSAGE);
            
        } catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error. Contact System Admin.");
    }
    }//GEN-LAST:event_b_removeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveVolunteer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveVolunteer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveVolunteer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveVolunteer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveVolunteer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_remove;
    private javax.swing.JComboBox<String> cb_Rdistrict;
    private javax.swing.JComboBox<String> cb_Rlocalbody;
    private javax.swing.JComboBox<String> cb_Rlocalbodytype;
    private javax.swing.JLabel img_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_District;
    private javax.swing.JLabel l_localbody;
    private javax.swing.JLabel l_localbody1;
    private javax.swing.JLabel l_regHealthWorkers;
    private javax.swing.JLabel l_title;
    private javax.swing.JLabel l_wokerID;
    private javax.swing.JLabel l_wokerID1;
    private javax.swing.JPanel p_main;
    private javax.swing.JPanel p_toppanel;
    private javax.swing.JScrollPane sp_healthWorkers;
    private javax.swing.JTable t_volunteers;
    private javax.swing.JTextField tf_volunteerid;
    private javax.swing.JTextField tf_volunteername;
    // End of variables declaration//GEN-END:variables
    String dist;
    String lb_type;
}
