/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asdtemp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ajayj
 */
public class testingcenter_citizen_dash extends javax.swing.JFrame {

    /**
     * Creates new form Sample
     */
    public testingcenter_citizen_dash() {
        initComponents();
        this.setLocationRelativeTo(null);
        count();
    }
    
    public void count()
    {
        dist_count= new String[15];
        for(int i=1;i<15;i++)
        {
            try
            {
                Connection con = new Connector().getCon();
                PreparedStatement stmt=con.prepareStatement("SELECT COUNT(tc_id) FROM asdproject.testing_centers WHERE tc_district_id=?;");
                stmt.setInt(1,i);
                ResultSet rs=stmt.executeQuery();
                rs.next();
                dist_count[i]=rs.getString(1);
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin.");
                break;
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Class Missing. Contact System Admin.");
                break;
            } catch(Exception ex) {
                JOptionPane.showMessageDialog(null,"Unknown Error. Contact System Admin.");
                break;
            }
        }
        l_trivandrum.setText(dist_count[1]);
        l_kollam.setText(dist_count[2]);
        l_pathanamthitta.setText(dist_count[3]);
        l_alappuzha.setText(dist_count[4]);
        l_kottayam.setText(dist_count[5]);
        l_idukki.setText(dist_count[6]);
        l_ernakulam.setText(dist_count[7]);
        l_thrissur.setText(dist_count[8]);
        l_palakkad.setText(dist_count[9]);
        l_malappuram.setText(dist_count[10]);
        l_kozhikode.setText(dist_count[11]);
        l_wayanad.setText(dist_count[12]);
        l_kannur.setText(dist_count[13]);
        l_kasargod.setText(dist_count[14]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        p_hdistrict21 = new javax.swing.JPanel();
        l_kozhikode = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        p_hdistrict14 = new javax.swing.JPanel();
        l_kollam = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        p_hdistrict15 = new javax.swing.JPanel();
        l_pathanamthitta = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        p_hdistrict16 = new javax.swing.JPanel();
        l_alappuzha = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        p_hdistrict17 = new javax.swing.JPanel();
        l_ernakulam = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        p_hdistrict18 = new javax.swing.JPanel();
        l_idukki = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        p_hdistrict19 = new javax.swing.JPanel();
        l_thrissur = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        p_hdistrict20 = new javax.swing.JPanel();
        l_palakkad = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        p_hdistrict22 = new javax.swing.JPanel();
        l_wayanad = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        p_hdistrict23 = new javax.swing.JPanel();
        l_kannur = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        p_hdistrict24 = new javax.swing.JPanel();
        l_kasargod = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        p_hdistrict26 = new javax.swing.JPanel();
        l_kottayam = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        p_hdistrict25 = new javax.swing.JPanel();
        l_malappuram = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        p_hdistrict = new javax.swing.JPanel();
        l_trivandrum = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1216, 644));

        jPanel2.setBackground(new java.awt.Color(46, 49, 49));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Testing Centers");

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/back2.png"))); // NOI18N
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(356, 356, 356)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel21)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        p_hdistrict21.setBackground(new java.awt.Color(255, 153, 204));
        p_hdistrict21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_hdistrict21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_hdistrict21MouseClicked(evt);
            }
        });

        l_kozhikode.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_kozhikode.setText("10");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("KOZHIKODE");

        javax.swing.GroupLayout p_hdistrict21Layout = new javax.swing.GroupLayout(p_hdistrict21);
        p_hdistrict21.setLayout(p_hdistrict21Layout);
        p_hdistrict21Layout.setHorizontalGroup(
            p_hdistrict21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict21Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(l_kozhikode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_hdistrict21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_hdistrict21Layout.setVerticalGroup(
            p_hdistrict21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict21Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(l_kozhikode)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(p_hdistrict21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(p_hdistrict21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        p_hdistrict14.setBackground(new java.awt.Color(255, 204, 0));
        p_hdistrict14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_hdistrict14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_hdistrict14MouseClicked(evt);
            }
        });

        l_kollam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_kollam.setText("10");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("KOLLAM");

        javax.swing.GroupLayout p_hdistrict14Layout = new javax.swing.GroupLayout(p_hdistrict14);
        p_hdistrict14.setLayout(p_hdistrict14Layout);
        p_hdistrict14Layout.setHorizontalGroup(
            p_hdistrict14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict14Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(l_kollam, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_hdistrict14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_hdistrict14Layout.setVerticalGroup(
            p_hdistrict14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict14Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(l_kollam)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        p_hdistrict15.setBackground(new java.awt.Color(0, 153, 204));
        p_hdistrict15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_hdistrict15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_hdistrict15MouseClicked(evt);
            }
        });

        l_pathanamthitta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_pathanamthitta.setText("10");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("PATHANAMTHITA");

        javax.swing.GroupLayout p_hdistrict15Layout = new javax.swing.GroupLayout(p_hdistrict15);
        p_hdistrict15.setLayout(p_hdistrict15Layout);
        p_hdistrict15Layout.setHorizontalGroup(
            p_hdistrict15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict15Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(l_pathanamthitta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_hdistrict15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_hdistrict15Layout.setVerticalGroup(
            p_hdistrict15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict15Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(l_pathanamthitta)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        p_hdistrict16.setBackground(new java.awt.Color(255, 255, 0));
        p_hdistrict16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_hdistrict16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_hdistrict16MouseClicked(evt);
            }
        });

        l_alappuzha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_alappuzha.setText("10");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("ALAPPUZHA");

        javax.swing.GroupLayout p_hdistrict16Layout = new javax.swing.GroupLayout(p_hdistrict16);
        p_hdistrict16.setLayout(p_hdistrict16Layout);
        p_hdistrict16Layout.setHorizontalGroup(
            p_hdistrict16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict16Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(l_alappuzha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_hdistrict16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_hdistrict16Layout.setVerticalGroup(
            p_hdistrict16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict16Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(l_alappuzha)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        p_hdistrict17.setBackground(new java.awt.Color(51, 204, 0));
        p_hdistrict17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_hdistrict17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_hdistrict17MouseClicked(evt);
            }
        });

        l_ernakulam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_ernakulam.setText("10");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("ERNAKULAM");

        javax.swing.GroupLayout p_hdistrict17Layout = new javax.swing.GroupLayout(p_hdistrict17);
        p_hdistrict17.setLayout(p_hdistrict17Layout);
        p_hdistrict17Layout.setHorizontalGroup(
            p_hdistrict17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict17Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(l_ernakulam, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_hdistrict17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_hdistrict17Layout.setVerticalGroup(
            p_hdistrict17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict17Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(l_ernakulam)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        p_hdistrict18.setBackground(new java.awt.Color(204, 0, 204));
        p_hdistrict18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_hdistrict18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_hdistrict18MouseClicked(evt);
            }
        });

        l_idukki.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_idukki.setText("10");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("IDUKKI");

        javax.swing.GroupLayout p_hdistrict18Layout = new javax.swing.GroupLayout(p_hdistrict18);
        p_hdistrict18.setLayout(p_hdistrict18Layout);
        p_hdistrict18Layout.setHorizontalGroup(
            p_hdistrict18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict18Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(l_idukki, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_hdistrict18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_hdistrict18Layout.setVerticalGroup(
            p_hdistrict18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict18Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(l_idukki)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        p_hdistrict19.setBackground(new java.awt.Color(204, 0, 51));
        p_hdistrict19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_hdistrict19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_hdistrict19MouseClicked(evt);
            }
        });

        l_thrissur.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_thrissur.setText("10");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("THRISSUR");

        javax.swing.GroupLayout p_hdistrict19Layout = new javax.swing.GroupLayout(p_hdistrict19);
        p_hdistrict19.setLayout(p_hdistrict19Layout);
        p_hdistrict19Layout.setHorizontalGroup(
            p_hdistrict19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict19Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(l_thrissur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_hdistrict19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_hdistrict19Layout.setVerticalGroup(
            p_hdistrict19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict19Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(l_thrissur)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        p_hdistrict20.setBackground(new java.awt.Color(0, 153, 255));
        p_hdistrict20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_hdistrict20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_hdistrict20MouseClicked(evt);
            }
        });

        l_palakkad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_palakkad.setText("10");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("PALAKKAD");

        javax.swing.GroupLayout p_hdistrict20Layout = new javax.swing.GroupLayout(p_hdistrict20);
        p_hdistrict20.setLayout(p_hdistrict20Layout);
        p_hdistrict20Layout.setHorizontalGroup(
            p_hdistrict20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict20Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(l_palakkad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_hdistrict20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_hdistrict20Layout.setVerticalGroup(
            p_hdistrict20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict20Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(l_palakkad)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        p_hdistrict22.setBackground(new java.awt.Color(204, 255, 255));
        p_hdistrict22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_hdistrict22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_hdistrict22MouseClicked(evt);
            }
        });

        l_wayanad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_wayanad.setText("10");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("WAYANAD");

        javax.swing.GroupLayout p_hdistrict22Layout = new javax.swing.GroupLayout(p_hdistrict22);
        p_hdistrict22.setLayout(p_hdistrict22Layout);
        p_hdistrict22Layout.setHorizontalGroup(
            p_hdistrict22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict22Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(l_wayanad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_hdistrict22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_hdistrict22Layout.setVerticalGroup(
            p_hdistrict22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict22Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(l_wayanad)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_hdistrict23.setBackground(new java.awt.Color(153, 204, 255));
        p_hdistrict23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_hdistrict23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_hdistrict23MouseClicked(evt);
            }
        });

        l_kannur.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_kannur.setText("10");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("KANNUR");

        javax.swing.GroupLayout p_hdistrict23Layout = new javax.swing.GroupLayout(p_hdistrict23);
        p_hdistrict23.setLayout(p_hdistrict23Layout);
        p_hdistrict23Layout.setHorizontalGroup(
            p_hdistrict23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict23Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(l_kannur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_hdistrict23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_hdistrict23Layout.setVerticalGroup(
            p_hdistrict23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict23Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(l_kannur)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_hdistrict24.setBackground(new java.awt.Color(204, 255, 204));
        p_hdistrict24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_hdistrict24.setFocusTraversalPolicyProvider(true);
        p_hdistrict24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_hdistrict24MouseClicked(evt);
            }
        });

        l_kasargod.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_kasargod.setText("10");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("KASARGOD");

        javax.swing.GroupLayout p_hdistrict24Layout = new javax.swing.GroupLayout(p_hdistrict24);
        p_hdistrict24.setLayout(p_hdistrict24Layout);
        p_hdistrict24Layout.setHorizontalGroup(
            p_hdistrict24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict24Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(l_kasargod, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_hdistrict24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_hdistrict24Layout.setVerticalGroup(
            p_hdistrict24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict24Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(l_kasargod)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        p_hdistrict26.setBackground(new java.awt.Color(0, 204, 204));
        p_hdistrict26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_hdistrict26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_hdistrict26MouseClicked(evt);
            }
        });

        l_kottayam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_kottayam.setText("10");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("KOTTAYAM");

        javax.swing.GroupLayout p_hdistrict26Layout = new javax.swing.GroupLayout(p_hdistrict26);
        p_hdistrict26.setLayout(p_hdistrict26Layout);
        p_hdistrict26Layout.setHorizontalGroup(
            p_hdistrict26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict26Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(l_kottayam, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_hdistrict26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_hdistrict26Layout.setVerticalGroup(
            p_hdistrict26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict26Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(l_kottayam)
                .addGap(18, 18, 18)
                .addComponent(jLabel29)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        p_hdistrict25.setBackground(new java.awt.Color(204, 204, 204));
        p_hdistrict25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_hdistrict25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_hdistrict25MouseClicked(evt);
            }
        });

        l_malappuram.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_malappuram.setText("10");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("MALAPPURAM");

        javax.swing.GroupLayout p_hdistrict25Layout = new javax.swing.GroupLayout(p_hdistrict25);
        p_hdistrict25.setLayout(p_hdistrict25Layout);
        p_hdistrict25Layout.setHorizontalGroup(
            p_hdistrict25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict25Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(l_malappuram, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_hdistrict25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_hdistrict25Layout.setVerticalGroup(
            p_hdistrict25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrict25Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(l_malappuram)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Testing Center Districtwise Statistics");

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/bullet.png"))); // NOI18N

        p_hdistrict.setBackground(new java.awt.Color(255, 0, 51));
        p_hdistrict.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_hdistrict.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_hdistrictMouseClicked(evt);
            }
        });

        l_trivandrum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_trivandrum.setText("10");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("THIRUVANTHAPURAM");

        javax.swing.GroupLayout p_hdistrictLayout = new javax.swing.GroupLayout(p_hdistrict);
        p_hdistrict.setLayout(p_hdistrictLayout);
        p_hdistrictLayout.setHorizontalGroup(
            p_hdistrictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrictLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(l_trivandrum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_hdistrictLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_hdistrictLayout.setVerticalGroup(
            p_hdistrictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hdistrictLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(l_trivandrum)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(p_hdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(p_hdistrict17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p_hdistrict14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_hdistrict18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_hdistrict22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p_hdistrict15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_hdistrict19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_hdistrict23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p_hdistrict24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p_hdistrict16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p_hdistrict20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p_hdistrict25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p_hdistrict26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(p_hdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_hdistrict14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_hdistrict15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_hdistrict16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_hdistrict26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p_hdistrict17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_hdistrict18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_hdistrict25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(p_hdistrict24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(p_hdistrict23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(p_hdistrict22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(p_hdistrict19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_hdistrict20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p_hdistrictMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_hdistrictMouseClicked
        // TODO add your handling code here:
        new Table_tc(1).setVisible(true);
    }//GEN-LAST:event_p_hdistrictMouseClicked

    private void p_hdistrict14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_hdistrict14MouseClicked
        // TODO add your handling code here:
        new Table_tc(2).setVisible(true);
    }//GEN-LAST:event_p_hdistrict14MouseClicked

    private void p_hdistrict15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_hdistrict15MouseClicked
        // TODO add your handling code here:
        new Table_tc(3).setVisible(true);
    }//GEN-LAST:event_p_hdistrict15MouseClicked

    private void p_hdistrict16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_hdistrict16MouseClicked
        // TODO add your handling code here:
        new Table_tc(4).setVisible(true);
    }//GEN-LAST:event_p_hdistrict16MouseClicked

    private void p_hdistrict26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_hdistrict26MouseClicked
        // TODO add your handling code here:
        new Table_tc(5).setVisible(true);
    }//GEN-LAST:event_p_hdistrict26MouseClicked

    private void p_hdistrict17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_hdistrict17MouseClicked
        // TODO add your handling code here:
        new Table_tc(7).setVisible(true);
    }//GEN-LAST:event_p_hdistrict17MouseClicked

    private void p_hdistrict18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_hdistrict18MouseClicked
        // TODO add your handling code here:
        new Table_tc(6).setVisible(true);
    }//GEN-LAST:event_p_hdistrict18MouseClicked

    private void p_hdistrict19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_hdistrict19MouseClicked
        // TODO add your handling code here:
        new Table_tc(8).setVisible(true);
    }//GEN-LAST:event_p_hdistrict19MouseClicked

    private void p_hdistrict20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_hdistrict20MouseClicked
        // TODO add your handling code here:
        new Table_tc(9).setVisible(true);
    }//GEN-LAST:event_p_hdistrict20MouseClicked

    private void p_hdistrict25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_hdistrict25MouseClicked
        // TODO add your handling code here:
        new Table_tc(10).setVisible(true);
    }//GEN-LAST:event_p_hdistrict25MouseClicked

    private void p_hdistrict21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_hdistrict21MouseClicked
        // TODO add your handling code here:
        new Table_tc(11).setVisible(true);
    }//GEN-LAST:event_p_hdistrict21MouseClicked

    private void p_hdistrict23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_hdistrict23MouseClicked
        // TODO add your handling code here:
        new Table_tc(13).setVisible(true);
    }//GEN-LAST:event_p_hdistrict23MouseClicked

    private void p_hdistrict22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_hdistrict22MouseClicked
        // TODO add your handling code here:
        new Table_tc(12).setVisible(true);
    }//GEN-LAST:event_p_hdistrict22MouseClicked

    private void p_hdistrict24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_hdistrict24MouseClicked
        // TODO add your handling code here:
        new Table_tc(14).setVisible(true);
    }//GEN-LAST:event_p_hdistrict24MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel32MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testingcenter_citizen_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testingcenter_citizen_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testingcenter_citizen_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testingcenter_citizen_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testingcenter_citizen_dash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel l_alappuzha;
    private javax.swing.JLabel l_ernakulam;
    private javax.swing.JLabel l_idukki;
    private javax.swing.JLabel l_kannur;
    private javax.swing.JLabel l_kasargod;
    private javax.swing.JLabel l_kollam;
    private javax.swing.JLabel l_kottayam;
    private javax.swing.JLabel l_kozhikode;
    private javax.swing.JLabel l_malappuram;
    private javax.swing.JLabel l_palakkad;
    private javax.swing.JLabel l_pathanamthitta;
    private javax.swing.JLabel l_thrissur;
    private javax.swing.JLabel l_trivandrum;
    private javax.swing.JLabel l_wayanad;
    private javax.swing.JPanel p_hdistrict;
    private javax.swing.JPanel p_hdistrict14;
    private javax.swing.JPanel p_hdistrict15;
    private javax.swing.JPanel p_hdistrict16;
    private javax.swing.JPanel p_hdistrict17;
    private javax.swing.JPanel p_hdistrict18;
    private javax.swing.JPanel p_hdistrict19;
    private javax.swing.JPanel p_hdistrict20;
    private javax.swing.JPanel p_hdistrict21;
    private javax.swing.JPanel p_hdistrict22;
    private javax.swing.JPanel p_hdistrict23;
    private javax.swing.JPanel p_hdistrict24;
    private javax.swing.JPanel p_hdistrict25;
    private javax.swing.JPanel p_hdistrict26;
    // End of variables declaration//GEN-END:variables
    String dist_count[];
}
