/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asdtemp;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author ajayj
 */
public class TestingCenters extends javax.swing.JFrame {

    /**
     * Creates new form CFLTCs
     */
    public TestingCenters() {
        initComponents();
        this.setLocationRelativeTo(null);
        fetch();
    }
    private void fetch()
{
    DefaultCategoryDataset barChartData= new DefaultCategoryDataset();
        
         try
        {
             Connection con=new Connector().getCon();
             PreparedStatement stmt= con.prepareStatement("SELECT count(tc.tc_id), d.dist_name from asdproject.testing_centers tc, asdproject.districts d where tc.tc_district_id=d.dist_id group by d.dist_name;");
             ResultSet rs=stmt.executeQuery();
             while(rs.next())
                  barChartData.setValue(rs.getInt(1), "Testing Center Count", rs.getString(2));
        }
       catch(Exception e)  
       {
           JOptionPane.showMessageDialog(null,"Chart Display Error");
       }        
        JFreeChart barChart= ChartFactory.createBarChart("Testing Centers District Wise Statistics", "District", "Count", barChartData, PlotOrientation.HORIZONTAL, false, true, false);      
        CategoryPlot barchrt= barChart.getCategoryPlot();
//        ((BarRenderer)barchrt.getRenderer()).setBarPainter(new StandardBarPainter());
//        BarRenderer r = (BarRenderer)barChart.getCategoryPlot().getRenderer();
//        r.setSeriesPaint(0, Color.black);
         NumberAxis yAxis = (NumberAxis) barchrt.getRangeAxis();
         yAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());
        barchrt.setRangeGridlinePaint(Color.ORANGE);
        
        ChartPanel barPanel= new ChartPanel(barChart);
        jPanel1.removeAll();
        jPanel1.add(barPanel, BorderLayout.CENTER);
        jPanel1.validate();
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_toppanel = new javax.swing.JPanel();
        p_title = new javax.swing.JLabel();
        img_back = new javax.swing.JLabel();
        p_sidepanel = new javax.swing.JPanel();
        p_add_testingcenter = new javax.swing.JPanel();
        l_add_cfltc = new javax.swing.JLabel();
        p_monitor_testingcenter = new javax.swing.JPanel();
        l_monitor_cfltc = new javax.swing.JLabel();
        p_remove_testingcenter = new javax.swing.JPanel();
        l_remove_cfltc = new javax.swing.JLabel();
        p_results_testingcenter = new javax.swing.JPanel();
        l_results = new javax.swing.JLabel();
        p_refresh_chart = new javax.swing.JPanel();
        l_results1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        p_toppanel.setBackground(new java.awt.Color(46, 49, 49));

        p_title.setBackground(new java.awt.Color(255, 255, 255));
        p_title.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        p_title.setForeground(new java.awt.Color(255, 255, 255));
        p_title.setText("Manage Testing Centers");

        img_back.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        img_back.setForeground(new java.awt.Color(255, 255, 255));
        img_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asdtemp/back2.png"))); // NOI18N
        img_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        img_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p_toppanelLayout = new javax.swing.GroupLayout(p_toppanel);
        p_toppanel.setLayout(p_toppanelLayout);
        p_toppanelLayout.setHorizontalGroup(
            p_toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_toppanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(img_back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p_title)
                .addContainerGap(533, Short.MAX_VALUE))
        );
        p_toppanelLayout.setVerticalGroup(
            p_toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_toppanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p_toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_title))
                .addGap(117, 117, 117))
        );

        getContentPane().add(p_toppanel);
        p_toppanel.setBounds(0, 0, 910, 60);

        p_sidepanel.setBackground(new java.awt.Color(46, 49, 49));
        p_sidepanel.setToolTipText("");
        p_sidepanel.setLayout(null);

        p_add_testingcenter.setBackground(new java.awt.Color(46, 49, 49));
        p_add_testingcenter.setForeground(new java.awt.Color(46, 49, 49));
        p_add_testingcenter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_add_testingcenter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_add_testingcenterMouseClicked(evt);
            }
        });

        l_add_cfltc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_add_cfltc.setForeground(new java.awt.Color(255, 255, 255));
        l_add_cfltc.setText("Add new ");

        javax.swing.GroupLayout p_add_testingcenterLayout = new javax.swing.GroupLayout(p_add_testingcenter);
        p_add_testingcenter.setLayout(p_add_testingcenterLayout);
        p_add_testingcenterLayout.setHorizontalGroup(
            p_add_testingcenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_add_testingcenterLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(l_add_cfltc)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        p_add_testingcenterLayout.setVerticalGroup(
            p_add_testingcenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_add_testingcenterLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_add_cfltc)
                .addContainerGap())
        );

        p_sidepanel.add(p_add_testingcenter);
        p_add_testingcenter.setBounds(0, 0, 250, 50);

        p_monitor_testingcenter.setBackground(new java.awt.Color(46, 49, 49));
        p_monitor_testingcenter.setForeground(new java.awt.Color(46, 49, 49));
        p_monitor_testingcenter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_monitor_testingcenter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_monitor_testingcenterMouseClicked(evt);
            }
        });

        l_monitor_cfltc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_monitor_cfltc.setForeground(new java.awt.Color(255, 255, 255));
        l_monitor_cfltc.setText("Monitor ");

        javax.swing.GroupLayout p_monitor_testingcenterLayout = new javax.swing.GroupLayout(p_monitor_testingcenter);
        p_monitor_testingcenter.setLayout(p_monitor_testingcenterLayout);
        p_monitor_testingcenterLayout.setHorizontalGroup(
            p_monitor_testingcenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_monitor_testingcenterLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(l_monitor_cfltc)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        p_monitor_testingcenterLayout.setVerticalGroup(
            p_monitor_testingcenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_monitor_testingcenterLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_monitor_cfltc)
                .addContainerGap())
        );

        p_sidepanel.add(p_monitor_testingcenter);
        p_monitor_testingcenter.setBounds(0, 50, 250, 49);

        p_remove_testingcenter.setBackground(new java.awt.Color(46, 49, 49));
        p_remove_testingcenter.setForeground(new java.awt.Color(46, 49, 49));
        p_remove_testingcenter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_remove_testingcenter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_remove_testingcenterMouseClicked(evt);
            }
        });

        l_remove_cfltc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_remove_cfltc.setForeground(new java.awt.Color(255, 255, 255));
        l_remove_cfltc.setText("Remove ");

        javax.swing.GroupLayout p_remove_testingcenterLayout = new javax.swing.GroupLayout(p_remove_testingcenter);
        p_remove_testingcenter.setLayout(p_remove_testingcenterLayout);
        p_remove_testingcenterLayout.setHorizontalGroup(
            p_remove_testingcenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_remove_testingcenterLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(l_remove_cfltc)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        p_remove_testingcenterLayout.setVerticalGroup(
            p_remove_testingcenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_remove_testingcenterLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_remove_cfltc)
                .addContainerGap())
        );

        p_sidepanel.add(p_remove_testingcenter);
        p_remove_testingcenter.setBounds(0, 100, 250, 50);

        p_results_testingcenter.setBackground(new java.awt.Color(46, 49, 49));
        p_results_testingcenter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_results_testingcenter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_results_testingcenterMouseClicked(evt);
            }
        });

        l_results.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_results.setForeground(new java.awt.Color(255, 255, 255));
        l_results.setText("Todays Result");

        javax.swing.GroupLayout p_results_testingcenterLayout = new javax.swing.GroupLayout(p_results_testingcenter);
        p_results_testingcenter.setLayout(p_results_testingcenterLayout);
        p_results_testingcenterLayout.setHorizontalGroup(
            p_results_testingcenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_results_testingcenterLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(l_results, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        p_results_testingcenterLayout.setVerticalGroup(
            p_results_testingcenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_results_testingcenterLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(l_results)
                .addContainerGap())
        );

        p_sidepanel.add(p_results_testingcenter);
        p_results_testingcenter.setBounds(0, 150, 250, 50);

        p_refresh_chart.setBackground(new java.awt.Color(46, 49, 49));
        p_refresh_chart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_refresh_chart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_refresh_chartMouseClicked(evt);
            }
        });

        l_results1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l_results1.setForeground(new java.awt.Color(255, 255, 255));
        l_results1.setText("Refresh Chart");

        javax.swing.GroupLayout p_refresh_chartLayout = new javax.swing.GroupLayout(p_refresh_chart);
        p_refresh_chart.setLayout(p_refresh_chartLayout);
        p_refresh_chartLayout.setHorizontalGroup(
            p_refresh_chartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_refresh_chartLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(l_results1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        p_refresh_chartLayout.setVerticalGroup(
            p_refresh_chartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_refresh_chartLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(l_results1)
                .addContainerGap())
        );

        p_sidepanel.add(p_refresh_chart);
        p_refresh_chart.setBounds(0, 200, 250, 50);

        getContentPane().add(p_sidepanel);
        p_sidepanel.setBounds(0, 60, 250, 1260);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1);
        jPanel1.setBounds(250, 60, 660, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p_add_testingcenterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add_testingcenterMouseClicked
        // TODO add your handling code here:
        new AddTestingCenter().setVisible(true);
    }//GEN-LAST:event_p_add_testingcenterMouseClicked

    private void p_monitor_testingcenterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_monitor_testingcenterMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_p_monitor_testingcenterMouseClicked

    private void p_remove_testingcenterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_remove_testingcenterMouseClicked
        // TODO add your handling code here:
        new RemoveTestingCenter().setVisible(true);
    }//GEN-LAST:event_p_remove_testingcenterMouseClicked

    private void p_results_testingcenterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_results_testingcenterMouseClicked
        // TODO add your handling code here:
        new TestResults().setVisible(true);
    }//GEN-LAST:event_p_results_testingcenterMouseClicked

    private void img_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_backMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_img_backMouseClicked

    private void p_refresh_chartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_refresh_chartMouseClicked
        // TODO add your handling code here:
        fetch();
        JOptionPane.showMessageDialog(null,"Chart Refreshed");
    }//GEN-LAST:event_p_refresh_chartMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestingCenters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestingCenters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestingCenters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestingCenters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestingCenters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img_back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_add_cfltc;
    private javax.swing.JLabel l_monitor_cfltc;
    private javax.swing.JLabel l_remove_cfltc;
    private javax.swing.JLabel l_results;
    private javax.swing.JLabel l_results1;
    private javax.swing.JPanel p_add_testingcenter;
    private javax.swing.JPanel p_monitor_testingcenter;
    private javax.swing.JPanel p_refresh_chart;
    private javax.swing.JPanel p_remove_testingcenter;
    private javax.swing.JPanel p_results_testingcenter;
    private javax.swing.JPanel p_sidepanel;
    private javax.swing.JLabel p_title;
    private javax.swing.JPanel p_toppanel;
    // End of variables declaration//GEN-END:variables
}
